/*
 * classElectroMeter.cpp
 *
 *  Created on: 03.07.2014
 *      Author: trofimenko
 */

#include "em.h"

Em::Em() : Device(EM_BEGIN)
{
 /*
	Parameter Parameters[EM_END - EM_BEGIN]=
	{
		// Идентификатор          		Доступ    			Операция   		 	Физический				Исп       			Знач 		Мин  	Макс
		{EM_FREQUENCY,					ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_FREQUENCY,		VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_CURRENT_PHASE_1,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_CURRENT,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_CURRENT_PHASE_2,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_CURRENT,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_CURRENT_PHASE_3,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_CURRENT,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_VOLTAGE_PHASE_1,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_VOLTAGE_PHASE_2,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_VOLTAGE_PHASE_3,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_VOLTAGE_PHASE_1_2,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_VOLTAGE_PHASE_2_3,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_VOLTAGE_PHASE_3_1,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_COS_PHI,					ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_NUMERIC,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_COS_PHI_PHASE_1,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_NUMERIC,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_COS_PHI_PHASE_2,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_NUMERIC,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_COS_PHI_PHASE_3,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_VOLTAGE,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_FULL_POWER,					ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_FULL_POWER,		VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_FULL_POWER_PHASE_1,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_FULL_POWER,		VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_FULL_POWER_PHASE_2,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_FULL_POWER,		VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_FULL_POWER_PHASE_3,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_FULL_POWER,		VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_POWER,				ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_POWER_PHASE_1,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_POWER_PHASE_2,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_POWER_PHASE_3,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_POWER,				ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_POWER_PHASE_1,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_POWER_PHASE_2,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_POWER_PHASE_3,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_ENERGY,				ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_ENERGY,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_PLUS_ALL,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_MINUS_ALL,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_PLUS_CUR_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_MINUS_CUR_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_PLUS_PREV_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_MINUS_PREV_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_PLUS_CUR_MONTH,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_MINUS_CUR_MONTH,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_PLUS_PREV_MONTH,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_ACTIVE_MINUS_PREV_MONTH,	ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_ACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_ENERGY,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_ENERGY,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_PLUS_ALL,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_MINUS_ALL,			ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_PLUS_CUR_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_MINUS_CUR_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_PLUS_PREV_DAY,		ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_MINUS_PREV_DAY,	ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_PLUS_CUR_MONTH,	ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_MINUS_CUR_MONTH,	ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_PLUS_PREV_MONTH,	ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_REACTIVE_MINUS_PREV_MONTH,	ACCESS_OPERATOR,	OPERATION_READ,		PHYSIC_REACTIVE_POWER,	VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_COEFFICIENT_TRANS_CURRENT,	ACCESS_OPERATOR,	OPERATION_WRITE,	PHYSIC_NUMERIC,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
		{EM_COEFFICIENT_TRANS_VOLTAGE,	ACCESS_OPERATOR,	OPERATION_WRITE,	PHYSIC_NUMERIC,			VALIDITY_ERROR,		0.0,		0.0,	100000.0},
	};
  */
}

Em::~Em()
{
	// TODO Auto-generated destructor stub
}

