#include "ccs.h"

void Ccs::initParameters()
{
  parameters_[CCS_BEGIN - CCS_BEGIN].id                = CCS_BEGIN;
  parameters_[CCS_BEGIN - CCS_BEGIN].access            = ACCESS_ERROR;
  parameters_[CCS_BEGIN - CCS_BEGIN].operation         = OPERATION_ERROR;
  parameters_[CCS_BEGIN - CCS_BEGIN].physic            = PHYSIC_ERROR;
  parameters_[CCS_BEGIN - CCS_BEGIN].validity          = VALIDITY_OK;
  parameters_[CCS_BEGIN - CCS_BEGIN].value.float_t         = 0.0;
  parameters_[CCS_BEGIN - CCS_BEGIN].min           = 0.0;
  parameters_[CCS_BEGIN - CCS_BEGIN].max           = 0.0;
  parameters_[CCS_BEGIN - CCS_BEGIN].def           = 0.0;

  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].id          = CCS_PASSWORD_LEVEL;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].access      = ACCESS_OPERATOR;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].operation   = OPERATION_WRITE;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].physic      = PHYSIC_NUMERIC;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].validity    = VALIDITY_ERROR;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].value.float_t   = ACCESS_OPERATOR;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].min     = ACCESS_ERROR;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].max     = ACCESS_LAST;
  parameters_[CCS_PASSWORD_LEVEL - CCS_BEGIN].def     = ACCESS_OPERATOR;

  parameters_[CCS_CONDITION - CCS_BEGIN].id          = CCS_CONDITION;
  parameters_[CCS_CONDITION - CCS_BEGIN].access      = ACCESS_OPERATOR;
  parameters_[CCS_CONDITION - CCS_BEGIN].operation   = OPERATION_WRITE;
  parameters_[CCS_CONDITION - CCS_BEGIN].physic      = PHYSIC_NUMERIC;
  parameters_[CCS_CONDITION - CCS_BEGIN].validity    = VALIDITY_OK;
  parameters_[CCS_CONDITION - CCS_BEGIN].value.float_t   = CCS_CONDITION_STOP;
  parameters_[CCS_CONDITION - CCS_BEGIN].min     = CCS_CONDITION_STOP;
  parameters_[CCS_CONDITION - CCS_BEGIN].max     = CCS_CONDITION_RUN;
  parameters_[CCS_CONDITION - CCS_BEGIN].def     = CCS_CONDITION_STOP;

  parameters_[CCS_WORKING_MODE - CCS_BEGIN].id          = CCS_WORKING_MODE;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].access      = ACCESS_OPERATOR;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].operation   = OPERATION_WRITE;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].physic      = PHYSIC_NUMERIC;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].validity    = VALIDITY_OK;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].value.float_t   = CCS_WORKING_MODE_MANUAL;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].min     = CCS_WORKING_MODE_MANUAL;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].max     = CCS_WORKING_MODE_PROGRAM;
  parameters_[CCS_WORKING_MODE - CCS_BEGIN].def     = CCS_WORKING_MODE_MANUAL;

  parameters_[CCS_CMD_STOP - CCS_BEGIN].id          = CCS_CMD_STOP;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].access      = ACCESS_OPERATOR;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].operation   = OPERATION_WRITE;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].physic      = PHYSIC_NUMERIC;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].validity    = VALIDITY_OK;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].value.float_t   = 0;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].min     = 0;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].max     = 1;
  parameters_[CCS_CMD_STOP - CCS_BEGIN].def     = 0;

  parameters_[CCS_CMD_START - CCS_BEGIN].id          = CCS_CMD_START;
  parameters_[CCS_CMD_START - CCS_BEGIN].access      = ACCESS_OPERATOR;
  parameters_[CCS_CMD_START - CCS_BEGIN].operation   = OPERATION_WRITE;
  parameters_[CCS_CMD_START - CCS_BEGIN].physic      = PHYSIC_NUMERIC;
  parameters_[CCS_CMD_START - CCS_BEGIN].validity    = VALIDITY_OK;
  parameters_[CCS_CMD_START - CCS_BEGIN].value.float_t   = 0;
  parameters_[CCS_CMD_START - CCS_BEGIN].min     = CmdStartNone;
  parameters_[CCS_CMD_START - CCS_BEGIN].max     = CmdStartRemote;
  parameters_[CCS_CMD_START - CCS_BEGIN].def     = CmdStartNone;

  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].id          = CCS_VSD_CONDITION;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].access      = ACCESS_OPERATOR;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].operation   = OPERATION_WRITE;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].physic      = PHYSIC_NUMERIC;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].validity    = VALIDITY_OK;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].value.float_t   = VSD_CONDITION_STOP;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].min     = VSD_CONDITION_STOP;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].max     = VSD_CONDITION_WAIT_RUN;
  parameters_[CCS_VSD_CONDITION - CCS_BEGIN].def     = VSD_CONDITION_STOP;

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_MODE, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_MODE, 2.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_MODE, 1);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_MODE, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_PREVENT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_PREVENT, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_PREVENT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_SETPOINT, 150.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_SETPOINT, 120.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_SETPOINT, 120.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_PARAMETER, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_PARAMETER, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_PARAMETER, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_STATE, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_STATE, 3.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_STATE, 3.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_STATE, 3.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_TIME, 0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_TIME, 0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_SUPPLY_OVERVOLTAGE_RESTART_FIRST_TIME, 86400.0);

  //-

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_MODE, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_MODE, 2.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_MODE, 1);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_MODE, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_PREVENT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_PREVENT, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_PREVENT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_SETPOINT, 80.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_SETPOINT, 80.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_PARAMETER, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_PARAMETER, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_PARAMETER, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_STATE, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_STATE, 3.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_STATE, 3.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_STATE, 3.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_TIME, 0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_TIME, 0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_SUPPLY_UNDERVOLTAGE_RESTART_FIRST_TIME, 86400.0);

  //-

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_MODE, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_MODE, 2.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_MODE, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_MODE, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PREVENT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PREVENT, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PREVENT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_SETPOINT, 20.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_SETPOINT, 20.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PARAMETER, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PARAMETER, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_PARAMETER, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_STATE, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_STATE, 3.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_STATE, 3.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_STATE, 3.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TIME, 0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TIME, 0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_RESTART_FIRST_TIME, 86400.0);

  //-

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_MODE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_MODE, 2.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_MODE, 1.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_MODE, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_PREVENT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_PREVENT, 1.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_PREVENT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_TRIP_SETPOINT, 80.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_TRIP_SETPOINT, 80.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_PARAMETER, 0.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_PARAMETER, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_PARAMETER, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_FLAG, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_FLAG, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_STATE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_STATE, 3.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_STATE, 3.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_STATE, 3.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_TIME, 0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_TIME, 0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OVERLOAD_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OVERLOAD_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_MOTOR_OVERLOAD_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_MOTOR_OVERLOAD_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_MOTOR_OVERLOAD_RESTART_FIRST_TIME, 86400.0);

  //-

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_MODE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_MODE, 2.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_MODE, 1.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_MODE, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_PREVENT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_PREVENT, 1.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_PREVENT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_TRIP_SETPOINT, 80.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_TRIP_SETPOINT, 80.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_PARAMETER, 0.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_PARAMETER, 0.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_PARAMETER, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_STATE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_STATE, 3.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_STATE, 3.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_STATE, 3.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_TIME, 0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_TIME, 0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_MOTOR_UNDERLOAD_RESTART_FIRST_TIME, 86400.0);

  // Защита "Дисбаланс токов двигателя"
  // Защита "Дисбаланс токов двигателя" - уставка "Режим реакции защиты"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_MODE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_MODE, 2.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_MODE, 1.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_MODE, 1.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Задержка активации защиты"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_ACTIV_DELAY, 60.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_ACTIV_DELAY, 15.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_ACTIV_DELAY, 15.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Задержка срабатывания защиты"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_DELAY, 60.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_DELAY, 20.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_DELAY, 20.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Задержка АПВ защиты"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_DELAY, 18000.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_DELAY, 3600.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Количество разрешенных АПВ"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_LIMIT, 9999.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_LIMIT, 5.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_LIMIT, 0.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Период сброса счётчиков АПВ"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_RESET, 599940.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_RESET, 86400.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_RESET, 86400.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Граница срабатывания защиты"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_SETPOINT, 15.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_SETPOINT, 15.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Граница разрешения АПВ"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_SETPOINT, 0.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_SETPOINT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_SETPOINT, 0.0);
  // Защита "Дисбаланс токов двигателя" - уставка "Флаг работы с ВРП"
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_PARAMETER, 0.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_PARAMETER, 0.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_PARAMETER, 0.0);
  // Защита "Дисбаланс токов двигателя" - Флаг что защита в АПВ
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FLAG, 0.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FLAG, 0.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FLAG, 0.0);
  // Защита "Дисбаланс токов двигателя" - состояние автомата защиты
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_STATE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_STATE, 3.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_STATE, 3.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_STATE, 3.0);
  // Защита "Дисбаланс токов двигателя" - значение внутреннего таймера
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TIME, 0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TIME, 0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_TIME, (uint32_t)0);
  // Защита "Дисбаланс токов двигателя" - значение счётчиков АПВ
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_COUNT, 9999.0);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_COUNT, 0.0);
  // Защита "Дисбаланс токов двигателя" - время первого АПВ
  setFieldPhysic(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FIRST_TIME, 0.0);
  setFieldMax(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FIRST_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FIRST_TIME, 0);
  setFieldValue(CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_FIRST_TIME, (uint32_t)0);

  //-

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_MODE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_MODE, 2.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_MODE, 1.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_MODE, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_PREVENT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_PREVENT, 1.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_PREVENT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_SETPOINT, 80.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_TRIP_SETPOINT, 80.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_PARAMETER, 0.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_PARAMETER, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_PARAMETER, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_STATE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_STATE, 3.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_STATE, 3.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_STATE, 3.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_TIME, 0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_TIME, 0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_MOTOR_OUT_OF_SYNC_RESTART_FIRST_TIME, 86400.0);

  //-

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_MODE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_MODE, 2.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_MODE, 1.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_MODE, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_PREVENT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_PREVENT, 1.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_PREVENT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_TRIP_SETPOINT, 80.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_TRIP_SETPOINT, 80.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_PARAMETER, 1.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_PARAMETER, 1.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_PARAMETER, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_STATE, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_STATE, 3.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_STATE, 3.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_STATE, 3.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_TIME, 0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_TIME, 0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_MOTOR_ASYNC_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_MOTOR_ASYNC_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_MOTOR_ASYNC_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_MOTOR_ASYNC_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_MOTOR_ASYNC_RESTART_FIRST_TIME, 86400.0);
  // Защита "Температура двигателя"
  // Защита "Температура двигателя" - уставка "Режим реакции защиты"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_MODE, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_MODE, 2.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_MODE, 1.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_MODE, 1.0);
  // Защита "Температура двигателя" - флаг запрещающего параметра
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_PREVENT, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_PREVENT, 1.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_PREVENT, 0.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_PREVENT, 0.0);
  // Защита "Температура двигателя" - уставка "Задержка активации защиты"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_ACTIV_DELAY, 60.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_ACTIV_DELAY, 0.0);
  // Защита "Температура двигателя" - уставка "Задержка срабатывания защиты"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_DELAY, 60.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_DELAY, 5.0);
  // Защита "Температура двигателя" - уставка "Задержка АПВ защиты"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_DELAY, 18000.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_DELAY, 3600.0);
  // Защита "Температура двигателя" - уставка "Количество разрешенных АПВ"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_LIMIT, 9999.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_LIMIT, 5.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_LIMIT, 5.0);
  // Защита "Температура двигателя" - уставка "Период сброса счётчиков АПВ"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_RESET, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_RESET, 599940.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_RESET, 86400.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_RESET, 86400.0);
  // Защита "Температура двигателя" - уставка "Граница срабатывания защиты"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_SETPOINT, PHYSIC_TEMPERATURE);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_SETPOINT, 150.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_SETPOINT, 115.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_TRIP_SETPOINT, 115.0);
  // Защита "Температура двигателя" - уставка "Граница разрешения АПВ"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_SETPOINT, PHYSIC_TEMPERATURE);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_SETPOINT, 150.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_SETPOINT, 115.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_SETPOINT, 115.0);
  // Защита "Температура двигателя" - уставка "Флаг работы с ВРП"
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_PARAMETER, 0.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_PARAMETER, 0.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_PARAMETER, 0.0);
  // Защита "Температура двигателя" - Флаг что защита в АПВ
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FLAG, 0.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FLAG, 0.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FLAG, 0.0);
  // Защита "Температура двигателя" - состояние автомата защиты
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_STATE, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_STATE, 3.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_STATE, 3.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_STATE, 3.0);
  // Защита "Температура двигателя" - значение внутреннего таймера
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_TIME, 0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_TIME, 0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_TIME, (uint32_t)0);
  // Защита "Температура двигателя" - значение счётчиков АПВ
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_COUNT, 9999.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_COUNT, 0.0);
  // Защита "Температура двигателя" - время первого АПВ
  setFieldPhysic(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FIRST_TIME, 0.0);
  setFieldMax(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FIRST_TIME, 4294967296.0);
  setFieldDef(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FIRST_TIME, 0.0);
  setFieldValue(CCS_PROT_DHS_TEMPERATURE_MOTOR_RESTART_FIRST_TIME, (uint32_t)0);

  //-

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_MODE, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_MODE, 2.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_MODE, 1.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_MODE, 1.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_PREVENT, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_PREVENT, 1.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_PREVENT, 0.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_PREVENT, 0.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_ACTIV_DELAY, 59999.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_ACTIV_DELAY, 0.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_DELAY, 600.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_DELAY, 5.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_DELAY, 5.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_DELAY, 60.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_DELAY, 86400.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_DELAY, 3600.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_DELAY, 3600.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_LIMIT, 99.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_LIMIT, 0.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_RESET, 60.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_RESET, 86400.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_RESET, 3600.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_RESET, 3600.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_SETPOINT, 80.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_TRIP_SETPOINT, 80.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_SETPOINT, 100.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_SETPOINT, 100.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_SETPOINT, 100.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_PARAMETER, 1.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_PARAMETER, 1.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_PARAMETER, 1.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FLAG, 1.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FLAG, 1.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FLAG, 1.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_STATE, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_STATE, 3.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_STATE, 3.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_STATE, 3.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_TIME, 0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_TIME, 0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_TIME, (uint32_t)0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_COUNT, 99.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_COUNT, 0.0);

  setFieldPhysic(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FIRST_TIME, 60.0);
  setFieldMax(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FIRST_TIME, 3599940.0);
  setFieldDef(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FIRST_TIME, 86400.0);
  setFieldValue(CCS_PROT_DHS_PRESSURE_INTAKE_RESTART_FIRST_TIME, 86400.0);

  /*
  // Защита "Температура двигателя"
  // Защита "Температура двигателя" - уставка "Режим реакции защиты"
  // Защита "Температура двигателя" - флаг запрещающего параметра
  // Защита "Температура двигателя" - уставка "Задержка активации защиты"
  // Защита "Температура двигателя" - уставка "Задержка срабатывания защиты"
  // Защита "Температура двигателя" - уставка "Задержка АПВ защиты"
  // Защита "Температура двигателя" - уставка "Количество разрешенных АПВ"
  // Защита "Температура двигателя" - уставка "Период сброса счётчиков АПВ"
  // Защита "Температура двигателя" - уставка "Граница срабатывания защиты"
  // Защита "Температура двигателя" - уставка "Граница разрешения АПВ"
  // Защита "Температура двигателя" - уставка "Флаг работы с ВРП"
  // Защита "Температура двигателя" - Флаг что защита в АПВ
  // Защита "Температура двигателя" - состояние автомата защиты
  // Защита "Температура двигателя" - значение внутреннего таймера
  // Защита "Температура двигателя" - значение счётчиков АПВ
  // Защита "Температура двигателя" - время первого АПВ
  */

  // Защита "Сопротивление изоляции"
  // Защита "Сопротивление изоляции" - уставка "Режим реакции защиты"
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_MODE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_MODE, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_MODE, 1.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_MODE, 1.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_MODE, 1.0);
  // Защита "Сопротивление изоляции" - флаг запрещающего параметра
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_PREVENT, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_PREVENT, 1.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_PREVENT, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_PREVENT, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Задержка активации защиты" всегда 0
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_ACTIV_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_ACTIV_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_ACTIV_DELAY, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_ACTIV_DELAY, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_ACTIV_DELAY, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Задержка срабатывания защиты" всегда 0
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_TRIP_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_TRIP_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_TRIP_DELAY, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_TRIP_DELAY, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_TRIP_DELAY, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Задержка АПВ защиты" всегда 0
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_DELAY, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_DELAY, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_DELAY, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_DELAY, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_DELAY, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Количество разрешенных АПВ" всегда 0
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_LIMIT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_LIMIT, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_LIMIT, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_LIMIT, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_LIMIT, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Период сброса счётчиков АПВ" всегда 0
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_RESET, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_RESET, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_RESET, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_RESET, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_RESET, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Граница срабатывания защиты"
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_TRIP_SETPOINT, PHYSIC_RESISTANCE);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_TRIP_SETPOINT, 30.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_TRIP_SETPOINT, 500.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_TRIP_SETPOINT, 30.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_TRIP_SETPOINT, 30.0);
  // Защита "Сопротивление изоляции" - уставка "Граница разрешения АПВ"
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_SETPOINT, PHYSIC_PERCENT);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_SETPOINT, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_SETPOINT, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_SETPOINT, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_SETPOINT, 0.0);
  // Защита "Сопротивление изоляции" - уставка "Флаг работы в режиме пониженной изоляции"
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_PARAMETER, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_PARAMETER, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_PARAMETER, 1.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_PARAMETER, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_PARAMETER, 0.0);
  // Защита "Сопротивление изоляции" - Флаг что защита в АПВ
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_FLAG, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_FLAG, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_FLAG, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_FLAG, 0.0);
  // Защита "Сопротивление изоляции" - состояние автомата защиты
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_STATE, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_STATE, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_STATE, 3.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_STATE, 3.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_STATE, 3.0);
  // Защита "Сопротивление изоляции" - значение внутреннего таймера
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_TIME, 0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_TIME, 0xFFFFFFFF);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_TIME, 0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_TIME, (uint32_t)0);
  // Защита "Сопротивление изоляции" - значение счётчиков АПВ
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_COUNT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_COUNT, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_COUNT, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_COUNT, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_COUNT, 0.0);
  // Защита "Сопротивление изоляции" - время первого АПВ
  setFieldPhysic(CCS_PROT_DHS_RESISTANCE_RESTART_FIRST_TIME, PHYSIC_TIME);
  setFieldMin(CCS_PROT_DHS_RESISTANCE_RESTART_FIRST_TIME, 0.0);
  setFieldMax(CCS_PROT_DHS_RESISTANCE_RESTART_FIRST_TIME, 0.0);
  setFieldDef(CCS_PROT_DHS_RESISTANCE_RESTART_FIRST_TIME, 0.0);
  setFieldValue(CCS_PROT_DHS_RESISTANCE_RESTART_FIRST_TIME, 0.0);

  //-

  setFieldPhysic(CCS_CONDITION_FLAG, PHYSIC_NUMERIC);
  setFieldMin(CCS_CONDITION_FLAG, 0.0);
  setFieldMax(CCS_CONDITION_FLAG, 4.0);
  setFieldDef(CCS_CONDITION_FLAG, 0.0);
  setFieldValue(CCS_CONDITION_FLAG, 0.0);

  setFieldPhysic(CCS_LAST_RUN_REASON_TMP, PHYSIC_NUMERIC);
  setFieldMin(CCS_LAST_RUN_REASON_TMP, LastReasonRunNone);
  setFieldMax(CCS_LAST_RUN_REASON_TMP, LastReasonRunMaxAnalog4);
  setFieldDef(CCS_LAST_RUN_REASON_TMP, LastReasonRunOperator);
  setFieldValue(CCS_LAST_RUN_REASON_TMP, (float)LastReasonRunOperator);

  setFieldPhysic(CCS_LAST_STOP_REASON_TMP, PHYSIC_NUMERIC);
  setFieldMin(CCS_LAST_STOP_REASON_TMP, LastReasonStopNone);
  setFieldMax(CCS_LAST_STOP_REASON_TMP, LastReasonStopMaxAnalog4);
  setFieldDef(CCS_LAST_STOP_REASON_TMP, LastReasonStopOperator);
  setFieldValue(CCS_LAST_STOP_REASON_TMP, (float)LastReasonStopOperator);

  setFieldPhysic(CCS_PROT_PREVENT, PHYSIC_NUMERIC);
  setFieldMin(CCS_PROT_PREVENT, 0.0);
  setFieldMax(CCS_PROT_PREVENT, 1.0);
  setFieldDef(CCS_PROT_PREVENT, 0.0);
  setFieldValue(CCS_PROT_PREVENT, 0.0);

  setFieldPhysic(CCS_TIMER_DIFFERENT_START, PHYSIC_TIME);
  setFieldMin(CCS_TIMER_DIFFERENT_START, 0.0);
  setFieldMax(CCS_TIMER_DIFFERENT_START, 3600.0);
  setFieldDef(CCS_TIMER_DIFFERENT_START, 60.0);
  setFieldValue(CCS_TIMER_DIFFERENT_START, 60.0);

  setFieldPhysic(CCS_COEF_OUT_CURRENT_1, PHYSIC_NUMERIC);
  setFieldMin(CCS_COEF_OUT_CURRENT_1, 0.001);
  setFieldMax(CCS_COEF_OUT_CURRENT_1, 10.0);
  setFieldDef(CCS_COEF_OUT_CURRENT_1, 1.0);
  setFieldValue(CCS_COEF_OUT_CURRENT_1, 1.0);

  setFieldPhysic(CCS_COEF_OUT_CURRENT_2, PHYSIC_NUMERIC);
  setFieldMin(CCS_COEF_OUT_CURRENT_2, 0.001);
  setFieldMax(CCS_COEF_OUT_CURRENT_2, 10.0);
  setFieldDef(CCS_COEF_OUT_CURRENT_2, 1.0);
  setFieldValue(CCS_COEF_OUT_CURRENT_2, 1.0);

  setFieldPhysic(CCS_COEF_OUT_CURRENT_3, PHYSIC_NUMERIC);
  setFieldMin(CCS_COEF_OUT_CURRENT_3, 0.001);
  setFieldMax(CCS_COEF_OUT_CURRENT_3, 10.0);
  setFieldDef(CCS_COEF_OUT_CURRENT_3, 1.0);
  setFieldValue(CCS_COEF_OUT_CURRENT_3, 1.0);

  setFieldPhysic(CCS_COEF_TRANSFORMATION, PHYSIC_NUMERIC);
  setFieldMin(CCS_COEF_TRANSFORMATION, 0.001);
  setFieldMax(CCS_COEF_TRANSFORMATION, 1000.0);
  setFieldDef(CCS_COEF_TRANSFORMATION, 1.0);
  setFieldValue(CCS_COEF_TRANSFORMATION, 1.0);
}
