#include "scada_telescop.h"

void ScadaTelescop::initParameters()
{
  countParameters_ = 183;
#ifdef USE_SERVER
  scadaParameters_ = new ScadaParameter[countParameters_];
#endif
  for (int i = 0; i < countParameters_; ++i) {
    scadaParameters_[i].value.uint32_t = 0;
  }

  // Состояние СУ
  scadaParameters_[0].id                 = 0;
  scadaParameters_[0].address            = 40000;
  scadaParameters_[0].operation          = OPERATION_READ;
  scadaParameters_[0].physic             = PHYSIC_NUMERIC;
  scadaParameters_[0].unit               = 0;
  scadaParameters_[0].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[0].coefficient        = 1;
  scadaParameters_[0].min                = 0;
  scadaParameters_[0].max                = 0;
  // Причина, мешающая запуску СУ
  scadaParameters_[1].id                 = 0;
  scadaParameters_[1].address            = 40001;
  scadaParameters_[1].operation          = OPERATION_READ;
  scadaParameters_[1].physic             = PHYSIC_NUMERIC;
  scadaParameters_[1].unit               = 0;
  scadaParameters_[1].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[1].coefficient        = 1;
  scadaParameters_[1].min                = 0;
  scadaParameters_[1].max                = 0;
  // Причина, мешающая запуску СУ
  scadaParameters_[2].id                 = 0;
  scadaParameters_[2].address            = 40002;
  scadaParameters_[2].operation          = OPERATION_READ;
  scadaParameters_[2].physic             = PHYSIC_NUMERIC;
  scadaParameters_[2].unit               = 0;
  scadaParameters_[2].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[2].coefficient        = 1;
  scadaParameters_[2].min                = 0;
  scadaParameters_[2].max                = 0;
  // Причина последнего останова
  scadaParameters_[3].id                 = 0;
  scadaParameters_[3].address            = 40003;
  scadaParameters_[3].operation          = OPERATION_READ;
  scadaParameters_[3].physic             = PHYSIC_NUMERIC;
  scadaParameters_[3].unit               = 0;
  scadaParameters_[3].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[3].coefficient        = 1;
  scadaParameters_[3].min                = 0;
  scadaParameters_[3].max                = 0;
  // Дата последнего останова
  scadaParameters_[4].id                 = 0;
  scadaParameters_[4].address            = 40004;
  scadaParameters_[4].operation          = OPERATION_READ;
  scadaParameters_[4].physic             = PHYSIC_NUMERIC;
  scadaParameters_[4].unit               = 0;
  scadaParameters_[4].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[4].coefficient        = 1;
  scadaParameters_[4].min                = 0;
  scadaParameters_[4].max                = 0;
  // Дата-время последнего останова
  scadaParameters_[5].id                 = 0;
  scadaParameters_[5].address            = 40005;
  scadaParameters_[5].operation          = OPERATION_READ;
  scadaParameters_[5].physic             = PHYSIC_NUMERIC;
  scadaParameters_[5].unit               = 0;
  scadaParameters_[5].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[5].coefficient        = 1;
  scadaParameters_[5].min                = 0;
  scadaParameters_[5].max                = 0;
  // Время последнего останова
  scadaParameters_[6].id                 = 0;
  scadaParameters_[6].address            = 40006;
  scadaParameters_[6].operation          = OPERATION_READ;
  scadaParameters_[6].physic             = PHYSIC_NUMERIC;
  scadaParameters_[6].unit               = 0;
  scadaParameters_[6].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[6].coefficient        = 1;
  scadaParameters_[6].min                = 0;
  scadaParameters_[6].max                = 0;
  // Время оставшееся до автозапуска(время АПВ)
  scadaParameters_[7].id                 = CCS_RESTART_TIMER;
  scadaParameters_[7].address            = 40007;
  scadaParameters_[7].operation          = OPERATION_READ;
  scadaParameters_[7].physic             = PHYSIC_TIME;
  scadaParameters_[7].unit               = TIME_MM;
  scadaParameters_[7].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[7].coefficient        = 1;
  scadaParameters_[7].min                = 0;
  scadaParameters_[7].max                = 0;
  // Межфазное напряжение Uin(AB)
  scadaParameters_[8].id                 = CCS_VOLTAGE_PHASE_1_2;
  scadaParameters_[8].address            = 40008;
  scadaParameters_[8].operation          = OPERATION_READ;
  scadaParameters_[8].physic             = PHYSIC_VOLTAGE;
  scadaParameters_[8].unit               = VOLTAGE_V;
  scadaParameters_[8].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[8].coefficient        = 1;
  scadaParameters_[8].min                = 0;
  scadaParameters_[8].max                = 10000;
  // Межфазное напряжение Uin(BC)
  scadaParameters_[9].id                 = CCS_VOLTAGE_PHASE_2_3;
  scadaParameters_[9].address            = 40009;
  scadaParameters_[9].operation          = OPERATION_READ;
  scadaParameters_[9].physic             = PHYSIC_VOLTAGE;
  scadaParameters_[9].unit               = VOLTAGE_V;
  scadaParameters_[9].typeData           = TYPE_DATA_UINT16;
  scadaParameters_[9].coefficient        = 1;
  scadaParameters_[9].min                = 0;
  scadaParameters_[9].max                = 10000;
  // Межфазное напряжение Uin(CA)
  scadaParameters_[10].id                = CCS_VOLTAGE_PHASE_3_1;
  scadaParameters_[10].address           = 40010;
  scadaParameters_[10].operation         = OPERATION_READ;
  scadaParameters_[10].physic            = PHYSIC_VOLTAGE;
  scadaParameters_[10].unit              = VOLTAGE_V;
  scadaParameters_[10].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[10].coefficient       = 1;
  scadaParameters_[10].min               = 0;
  scadaParameters_[10].max               = 10000;
  // Дисбаланс входного напряжения dUin
  scadaParameters_[11].id                = CCS_VOLTAGE_IMBALANCE_IN;
  scadaParameters_[11].address           = 40011;
  scadaParameters_[11].operation         = OPERATION_READ;
  scadaParameters_[11].physic            = PHYSIC_PERCENT;
  scadaParameters_[11].unit              = PERCENT_PERCENT;
  scadaParameters_[11].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[11].coefficient       = 1;
  scadaParameters_[11].min               = 0;
  scadaParameters_[11].max               = 100;
  // Ток двигателя фаза 1
  scadaParameters_[12].id                = CCS_MOTOR_CURRENT_PHASE_1;
  scadaParameters_[12].address           = 40012;
  scadaParameters_[12].operation         = OPERATION_READ;
  scadaParameters_[12].physic            = PHYSIC_CURRENT;
  scadaParameters_[12].unit              = CURRENT_A;
  scadaParameters_[12].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[12].coefficient       = 0.1;
  scadaParameters_[12].min               = 0;
  scadaParameters_[12].max               = 65535;
  // Ток двигателя фаза 2
  scadaParameters_[13].id                = CCS_MOTOR_CURRENT_PHASE_2;
  scadaParameters_[13].address           = 40013;
  scadaParameters_[13].operation         = OPERATION_READ;
  scadaParameters_[13].physic            = PHYSIC_CURRENT;
  scadaParameters_[13].unit              = CURRENT_A;
  scadaParameters_[13].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[13].coefficient       = 0.1;
  scadaParameters_[13].min               = 0;
  scadaParameters_[13].max               = 65535;
  // Ток двигателя фаза 3
  scadaParameters_[14].id                = CCS_MOTOR_CURRENT_PHASE_3;
  scadaParameters_[14].address           = 40014;
  scadaParameters_[14].operation         = OPERATION_READ;
  scadaParameters_[14].physic            = PHYSIC_CURRENT;
  scadaParameters_[14].unit              = CURRENT_A;
  scadaParameters_[14].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[14].coefficient       = 0.1;
  scadaParameters_[14].min               = 0;
  scadaParameters_[14].max               = 65535;
  // Дисбаланс токов
  scadaParameters_[15].id                = CCS_MOTOR_CURRENT_IMBALANCE;
  scadaParameters_[15].address           = 40015;
  scadaParameters_[15].operation         = OPERATION_READ;
  scadaParameters_[15].physic            = PHYSIC_PERCENT;
  scadaParameters_[15].unit              = PERCENT_PERCENT;
  scadaParameters_[15].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[15].coefficient       = 1;
  scadaParameters_[15].min               = 0;
  scadaParameters_[15].max               = 100;
  // Полная мощность
  scadaParameters_[16].id                = VSD_POWER_FULL;
  scadaParameters_[16].address           = 40016;
  scadaParameters_[16].operation         = OPERATION_READ;
  scadaParameters_[16].physic            = PHYSIC_FULL_POWER;
  scadaParameters_[16].unit              = FULL_POWER_KVA;
  scadaParameters_[16].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[16].coefficient       = 0.1;
  scadaParameters_[16].min               = 0;
  scadaParameters_[16].max               = 10000;
  // Коэф. Мощности
  scadaParameters_[17].id                = CCS_MOTOR_COS_PHI_NOW;
  scadaParameters_[17].address           = 40017;
  scadaParameters_[17].operation         = OPERATION_READ;
  scadaParameters_[17].physic            = PHYSIC_NUMERIC;
  scadaParameters_[17].unit              = 0;
  scadaParameters_[17].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[17].coefficient       = 0.01;
  scadaParameters_[17].min               = 0;
  scadaParameters_[17].max               = 65535;
  // Загрузка двигателя
  scadaParameters_[18].id                = CCS_MOTOR_LOAD_NOW;
  scadaParameters_[18].address           = 40018;
  scadaParameters_[18].operation         = OPERATION_READ;
  scadaParameters_[18].physic            = PHYSIC_PERCENT;
  scadaParameters_[18].unit              = PERCENT_PERCENT;
  scadaParameters_[18].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[18].coefficient       = 1;
  scadaParameters_[18].min               = 0;
  scadaParameters_[18].max               = 200;
  // Сопротивление изоляции Rinsul
  scadaParameters_[19].id                = CCS_RESISTANCE_ISOLATION;
  scadaParameters_[19].address           = 40019;
  scadaParameters_[19].operation         = OPERATION_READ;
  scadaParameters_[19].physic            = PHYSIC_RESISTANCE;
  scadaParameters_[19].unit              = RESISTANCE_KOM;
  scadaParameters_[19].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[19].coefficient       = 1;
  scadaParameters_[19].min               = 0;
  scadaParameters_[19].max               = 9999;
  // Частота турбинного вращения
  scadaParameters_[20].id                = CCS_TURBO_ROTATION_NOW;
  scadaParameters_[20].address           = 40020;
  scadaParameters_[20].operation         = OPERATION_READ;
  scadaParameters_[20].physic            = PHYSIC_FREQUENCY;
  scadaParameters_[20].unit              = FREQUENCY_HZ;
  scadaParameters_[20].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[20].coefficient       = 1;
  scadaParameters_[20].min               = 0;
  scadaParameters_[20].max               = 8000;
  // Выходная частота ПЧ
  scadaParameters_[21].id                = VSD_FREQUENCY_NOW;
  scadaParameters_[21].address           = 40021;
  scadaParameters_[21].operation         = OPERATION_READ;
  scadaParameters_[21].physic            = PHYSIC_FREQUENCY;
  scadaParameters_[21].unit              = FREQUENCY_HZ;
  scadaParameters_[21].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[21].coefficient       = 0.01;
  scadaParameters_[21].min               = 0;
  scadaParameters_[21].max               = 20000;
  // Выходное напряжение ПЧ
  scadaParameters_[22].id                = VSD_VOLTAGE_LINE;
  scadaParameters_[22].address           = 40022;
  scadaParameters_[22].operation         = OPERATION_READ;
  scadaParameters_[22].physic            = PHYSIC_VOLTAGE;
  scadaParameters_[22].unit              = VOLTAGE_V;
  scadaParameters_[22].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[22].coefficient       = 1;
  scadaParameters_[22].min               = 0;
  scadaParameters_[22].max               = 10000;
  // Напряжение на выходе ТМПН
  scadaParameters_[23].id                = CCS_TRANS_OUTPUT_VOLTAGE_LINE;
  scadaParameters_[23].address           = 40023;
  scadaParameters_[23].operation         = OPERATION_READ;
  scadaParameters_[23].physic            = PHYSIC_VOLTAGE;
  scadaParameters_[23].unit              = VOLTAGE_V;
  scadaParameters_[23].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[23].coefficient       = 1;
  scadaParameters_[23].min               = 0;
  scadaParameters_[23].max               = 10000;
  // Ток в звене постоянного тока Id
  scadaParameters_[24].id                = VSD_CURRENT_DC;
  scadaParameters_[24].address           = 40024;
  scadaParameters_[24].operation         = OPERATION_READ;
  scadaParameters_[24].physic            = PHYSIC_CURRENT;
  scadaParameters_[24].unit              = CURRENT_A;
  scadaParameters_[24].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[24].coefficient       = 1;
  scadaParameters_[24].min               = 0;
  scadaParameters_[24].max               = 0;
  // Напряжение цепи постоянного тока Ud
  scadaParameters_[25].id                = VSD_VOLTAGE_DC;
  scadaParameters_[25].address           = 40025;
  scadaParameters_[25].operation         = OPERATION_READ;
  scadaParameters_[25].physic            = PHYSIC_VOLTAGE;
  scadaParameters_[25].unit              = VOLTAGE_V;
  scadaParameters_[25].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[25].coefficient       = 1;
  scadaParameters_[25].min               = 0;
  scadaParameters_[25].max               = 10000;
  // Время работы в часах
  scadaParameters_[26].id                = CCS_GENERAL_RUN_DATE_TIME;
  scadaParameters_[26].address           = 40026;
  scadaParameters_[26].operation         = OPERATION_READ;
  scadaParameters_[26].physic            = PHYSIC_TIME;
  scadaParameters_[26].unit              = TIME_HH;
  scadaParameters_[26].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[26].coefficient       = 1;
  scadaParameters_[26].min               = 0;
  scadaParameters_[26].max               = 999999;
  // Общее количество запусков насоса
  scadaParameters_[27].id                = CCS_COUNT_START;
  scadaParameters_[27].address           = 40027;
  scadaParameters_[27].operation         = OPERATION_READ;
  scadaParameters_[27].physic            = PHYSIC_NUMERIC;
  scadaParameters_[27].unit              = 0;
  scadaParameters_[27].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[27].coefficient       = 1;
  scadaParameters_[27].min               = 0;
  scadaParameters_[27].max               = 999999;
  // Динамический уровень
  scadaParameters_[28].id                = -1;
  scadaParameters_[28].address           = 40028;
  scadaParameters_[28].operation         = OPERATION_READ;
  scadaParameters_[28].physic            = PHYSIC_NUMERIC;
  scadaParameters_[28].unit              = 0;
  scadaParameters_[28].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[28].coefficient       = 1;
  scadaParameters_[28].min               = 0;
  scadaParameters_[28].max               = 0;
  // Устьевое давление
  scadaParameters_[29].id                = -1;
  scadaParameters_[29].address           = 40029;
  scadaParameters_[29].operation         = OPERATION_READ;
  scadaParameters_[29].physic            = PHYSIC_PRESSURE;
  scadaParameters_[29].unit              = PRESSURE_AT;
  scadaParameters_[29].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[29].coefficient       = 1;
  scadaParameters_[29].min               = 0;
  scadaParameters_[29].max               = 0;
  // Затрубное давление
  scadaParameters_[30].id                = -1;
  scadaParameters_[30].address           = 40030;
  scadaParameters_[30].operation         = OPERATION_READ;
  scadaParameters_[30].physic            = PHYSIC_PRESSURE;
  scadaParameters_[30].unit              = PRESSURE_AT;
  scadaParameters_[30].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[30].coefficient       = 1;
  scadaParameters_[30].min               = 0;
  scadaParameters_[30].max               = 0;
  // Линейное давление
  scadaParameters_[31].id                = -1;
  scadaParameters_[31].address           = 40031;
  scadaParameters_[31].operation         = OPERATION_READ;
  scadaParameters_[31].physic            = PHYSIC_PRESSURE;
  scadaParameters_[31].unit              = PRESSURE_AT;
  scadaParameters_[31].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[31].coefficient       = 1;
  scadaParameters_[31].min               = 0;
  scadaParameters_[31].max               = 0;
  // Давление на приеме
  scadaParameters_[32].id                = TMS_PRESSURE_INTAKE;
  scadaParameters_[32].address           = 40032;
  scadaParameters_[32].operation         = OPERATION_READ;
  scadaParameters_[32].physic            = PHYSIC_PRESSURE;
  scadaParameters_[32].unit              = PRESSURE_AT;
  scadaParameters_[32].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[32].coefficient       = 0.01;
  scadaParameters_[32].min               = 0;
  scadaParameters_[32].max               = 40;
  // Показания расходомера БИГР
  scadaParameters_[33].id                = TMS_FLOW_DISCHARGE;
  scadaParameters_[33].address           = 40033;
  scadaParameters_[33].operation         = OPERATION_READ;
  scadaParameters_[33].physic            = PHYSIC_FLOW;
  scadaParameters_[33].unit              = FLOW_M3_DD;
  scadaParameters_[33].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[33].coefficient       = 1;
  scadaParameters_[33].min               = 0;
  scadaParameters_[33].max               = 0;
  // Температура обмоток двигателя Tw
  scadaParameters_[34].id                = TMS_TEMPERATURE_WINDING;
  scadaParameters_[34].address           = 40034;
  scadaParameters_[34].operation         = OPERATION_READ;
  scadaParameters_[34].physic            = PHYSIC_TEMPERATURE;
  scadaParameters_[34].unit              = TEMPERATURE_C;
  scadaParameters_[34].typeData          = TYPE_DATA_INT16;
  scadaParameters_[34].coefficient       = 1;
  scadaParameters_[34].min               = 0;
  scadaParameters_[34].max               = 300;
  // Температура на приеме Tin
  scadaParameters_[35].id                = TMS_TEMPERATURE_INTAKE;
  scadaParameters_[35].address           = 40035;
  scadaParameters_[35].operation         = OPERATION_READ;
  scadaParameters_[35].physic            = PHYSIC_TEMPERATURE;
  scadaParameters_[35].unit              = TEMPERATURE_C;
  scadaParameters_[35].typeData          = TYPE_DATA_INT16;
  scadaParameters_[35].coefficient       = 1;
  scadaParameters_[35].min               = 0;
  scadaParameters_[35].max               = 150;
  // Давление на выкиде насоса
  scadaParameters_[36].id                = TMS_PRESSURE_DISCHARGE;
  scadaParameters_[36].address           = 40036;
  scadaParameters_[36].operation         = OPERATION_READ;
  scadaParameters_[36].physic            = PHYSIC_PRESSURE;
  scadaParameters_[36].unit              = PRESSURE_AT;
  scadaParameters_[36].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[36].coefficient       = 1;
  scadaParameters_[36].min               = 0;
  scadaParameters_[36].max               = 40;
  // Количество качаний в минуту
  scadaParameters_[37].id                = -1;
  scadaParameters_[37].address           = 40037;
  scadaParameters_[37].operation         = OPERATION_READ;
  scadaParameters_[37].physic            = 0;
  scadaParameters_[37].unit              = 0;
  scadaParameters_[37].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[37].coefficient       = 1;
  scadaParameters_[37].min               = 0;
  scadaParameters_[37].max               = 0;
  // Вибрация насоса радиальная Vradial
  scadaParameters_[38].id                = TMS_ACCELERATION_XY_INTAKE;
  scadaParameters_[38].address           = 40038;
  scadaParameters_[38].operation         = OPERATION_READ;
  scadaParameters_[38].physic            = PHYSIC_ACCELERATION;
  scadaParameters_[38].unit              = ACCELERATION_MSS2;
  scadaParameters_[38].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[38].coefficient       = 1;
  scadaParameters_[38].min               = 0;
  scadaParameters_[38].max               = 40;
  // Вибрация насоса осевая Vaxial
  scadaParameters_[39].id                = TMS_ACCELERATION_Z_INTAKE;
  scadaParameters_[39].address           = 40039;
  scadaParameters_[39].operation         = OPERATION_READ;
  scadaParameters_[39].physic            = PHYSIC_ACCELERATION;
  scadaParameters_[39].unit              = ACCELERATION_MSS2;
  scadaParameters_[39].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[39].coefficient       = 1;
  scadaParameters_[39].min               = 0;
  scadaParameters_[39].max               = 40;
  // 
  scadaParameters_[40].id                = -1;
  scadaParameters_[40].address           = 40040;
  scadaParameters_[40].operation         = OPERATION_READ;
  scadaParameters_[40].physic            = 0;
  scadaParameters_[40].unit              = 0;
  scadaParameters_[40].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[40].coefficient       = 1;
  scadaParameters_[40].min               = 0;
  scadaParameters_[40].max               = 0;
  // 
  scadaParameters_[41].id                = -1;
  scadaParameters_[41].address           = 40041;
  scadaParameters_[41].operation         = OPERATION_READ;
  scadaParameters_[41].physic            = 0;
  scadaParameters_[41].unit              = 0;
  scadaParameters_[41].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[41].coefficient       = 1;
  scadaParameters_[41].min               = 0;
  scadaParameters_[41].max               = 0;
  // А+ за весь период
  scadaParameters_[42].id                = EM_ACTIVE_PLUS_ALL;
  scadaParameters_[42].address           = 40042;
  scadaParameters_[42].operation         = OPERATION_READ;
  scadaParameters_[42].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[42].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[42].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[42].coefficient       = 0.1;
  scadaParameters_[42].min               = 0;
  scadaParameters_[42].max               = 0;
  // А- за весь период
  scadaParameters_[43].id                = EM_ACTIVE_MINUS_ALL;
  scadaParameters_[43].address           = 40044;
  scadaParameters_[43].operation         = OPERATION_READ;
  scadaParameters_[43].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[43].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[43].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[43].coefficient       = 0.1;
  scadaParameters_[43].min               = 0;
  scadaParameters_[43].max               = 0;
  // R+ за весь период
  scadaParameters_[44].id                = EM_REACTIVE_PLUS_ALL;
  scadaParameters_[44].address           = 40046;
  scadaParameters_[44].operation         = OPERATION_READ;
  scadaParameters_[44].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[44].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[44].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[44].coefficient       = 0.1;
  scadaParameters_[44].min               = 0;
  scadaParameters_[44].max               = 0;
  // R- за весь период
  scadaParameters_[45].id                = EM_REACTIVE_MINUS_ALL;
  scadaParameters_[45].address           = 40048;
  scadaParameters_[45].operation         = OPERATION_READ;
  scadaParameters_[45].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[45].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[45].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[45].coefficient       = 0.1;
  scadaParameters_[45].min               = 0;
  scadaParameters_[45].max               = 0;
  // R1 за весь период
  scadaParameters_[46].id                = -1;
  scadaParameters_[46].address           = 40050;
  scadaParameters_[46].operation         = OPERATION_READ;
  scadaParameters_[46].physic            = 0;
  scadaParameters_[46].unit              = 0;
  scadaParameters_[46].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[46].coefficient       = 0.1;
  scadaParameters_[46].min               = 0;
  scadaParameters_[46].max               = 0;
  // R2 за весь период
  scadaParameters_[47].id                = -1;
  scadaParameters_[47].address           = 40052;
  scadaParameters_[47].operation         = OPERATION_READ;
  scadaParameters_[47].physic            = 0;
  scadaParameters_[47].unit              = 0;
  scadaParameters_[47].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[47].coefficient       = 0.1;
  scadaParameters_[47].min               = 0;
  scadaParameters_[47].max               = 0;
  // R3 за весь период
  scadaParameters_[48].id                = -1;
  scadaParameters_[48].address           = 40054;
  scadaParameters_[48].operation         = OPERATION_READ;
  scadaParameters_[48].physic            = 0;
  scadaParameters_[48].unit              = 0;
  scadaParameters_[48].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[48].coefficient       = 0.1;
  scadaParameters_[48].min               = 0;
  scadaParameters_[48].max               = 0;
  // R4 за весь период
  scadaParameters_[49].id                = -1;
  scadaParameters_[49].address           = 40056;
  scadaParameters_[49].operation         = OPERATION_READ;
  scadaParameters_[49].physic            = 0;
  scadaParameters_[49].unit              = 0;
  scadaParameters_[49].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[49].coefficient       = 0.1;
  scadaParameters_[49].min               = 0;
  scadaParameters_[49].max               = 0;
  // А+ за текущие сутки
  scadaParameters_[50].id                = EM_ACTIVE_PLUS_CUR_DAY;
  scadaParameters_[50].address           = 40058;
  scadaParameters_[50].operation         = OPERATION_READ;
  scadaParameters_[50].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[50].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[50].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[50].coefficient       = 0.1;
  scadaParameters_[50].min               = 0;
  scadaParameters_[50].max               = 0;
  // А- за текущие сутки
  scadaParameters_[51].id                = EM_ACTIVE_MINUS_CUR_DAY;
  scadaParameters_[51].address           = 40060;
  scadaParameters_[51].operation         = OPERATION_READ;
  scadaParameters_[51].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[51].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[51].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[51].coefficient       = 0.1;
  scadaParameters_[51].min               = 0;
  scadaParameters_[51].max               = 0;
  // R+ за текущие сутки
  scadaParameters_[52].id                = EM_REACTIVE_PLUS_CUR_DAY;
  scadaParameters_[52].address           = 40062;
  scadaParameters_[52].operation         = OPERATION_READ;
  scadaParameters_[52].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[52].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[52].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[52].coefficient       = 0.1;
  scadaParameters_[52].min               = 0;
  scadaParameters_[52].max               = 0;
  // R- за текущие сутки
  scadaParameters_[53].id                = EM_REACTIVE_MINUS_CUR_DAY;
  scadaParameters_[53].address           = 40064;
  scadaParameters_[53].operation         = OPERATION_READ;
  scadaParameters_[53].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[53].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[53].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[53].coefficient       = 0.1;
  scadaParameters_[53].min               = 0;
  scadaParameters_[53].max               = 0;
  // R1 за текущие сутки
  scadaParameters_[54].id                = -1;
  scadaParameters_[54].address           = 40066;
  scadaParameters_[54].operation         = OPERATION_READ;
  scadaParameters_[54].physic            = 0;
  scadaParameters_[54].unit              = 0;
  scadaParameters_[54].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[54].coefficient       = 0.1;
  scadaParameters_[54].min               = 0;
  scadaParameters_[54].max               = 0;
  // R2 за текущие сутки
  scadaParameters_[55].id                = -1;
  scadaParameters_[55].address           = 40068;
  scadaParameters_[55].operation         = OPERATION_READ;
  scadaParameters_[55].physic            = 0;
  scadaParameters_[55].unit              = 0;
  scadaParameters_[55].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[55].coefficient       = 0.1;
  scadaParameters_[55].min               = 0;
  scadaParameters_[55].max               = 0;
  // R3 за текущие сутки
  scadaParameters_[56].id                = -1;
  scadaParameters_[56].address           = 40070;
  scadaParameters_[56].operation         = OPERATION_READ;
  scadaParameters_[56].physic            = 0;
  scadaParameters_[56].unit              = 0;
  scadaParameters_[56].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[56].coefficient       = 0.1;
  scadaParameters_[56].min               = 0;
  scadaParameters_[56].max               = 0;
  // R4 за текущие сутки
  scadaParameters_[57].id                = -1;
  scadaParameters_[57].address           = 40072;
  scadaParameters_[57].operation         = OPERATION_READ;
  scadaParameters_[57].physic            = 0;
  scadaParameters_[57].unit              = 0;
  scadaParameters_[57].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[57].coefficient       = 0.1;
  scadaParameters_[57].min               = 0;
  scadaParameters_[57].max               = 0;
  // А+ за предыдущие сутки
  scadaParameters_[58].id                = EM_ACTIVE_PLUS_PREV_DAY;
  scadaParameters_[58].address           = 40074;
  scadaParameters_[58].operation         = OPERATION_READ;
  scadaParameters_[58].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[58].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[58].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[58].coefficient       = 0.1;
  scadaParameters_[58].min               = 0;
  scadaParameters_[58].max               = 0;
  // А- за предыдущие сутки
  scadaParameters_[59].id                = EM_ACTIVE_MINUS_PREV_DAY;
  scadaParameters_[59].address           = 40076;
  scadaParameters_[59].operation         = OPERATION_READ;
  scadaParameters_[59].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[59].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[59].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[59].coefficient       = 0.1;
  scadaParameters_[59].min               = 0;
  scadaParameters_[59].max               = 0;
  // R+ за предыдущие сутки
  scadaParameters_[60].id                = EM_REACTIVE_PLUS_PREV_DAY;
  scadaParameters_[60].address           = 40078;
  scadaParameters_[60].operation         = OPERATION_READ;
  scadaParameters_[60].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[60].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[60].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[60].coefficient       = 0.1;
  scadaParameters_[60].min               = 0;
  scadaParameters_[60].max               = 0;
  // R- за предыдущие сутки
  scadaParameters_[61].id                = EM_REACTIVE_MINUS_PREV_DAY;
  scadaParameters_[61].address           = 40080;
  scadaParameters_[61].operation         = OPERATION_READ;
  scadaParameters_[61].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[61].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[61].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[61].coefficient       = 0.1;
  scadaParameters_[61].min               = 0;
  scadaParameters_[61].max               = 0;
  // R1 за предыдущие сутки
  scadaParameters_[62].id                = -1;
  scadaParameters_[62].address           = 40082;
  scadaParameters_[62].operation         = OPERATION_READ;
  scadaParameters_[62].physic            = 0;
  scadaParameters_[62].unit              = 0;
  scadaParameters_[62].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[62].coefficient       = 0.1;
  scadaParameters_[62].min               = 0;
  scadaParameters_[62].max               = 0;
  // R2 за предыдущие сутки
  scadaParameters_[63].id                = -1;
  scadaParameters_[63].address           = 40084;
  scadaParameters_[63].operation         = OPERATION_READ;
  scadaParameters_[63].physic            = 0;
  scadaParameters_[63].unit              = 0;
  scadaParameters_[63].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[63].coefficient       = 0.1;
  scadaParameters_[63].min               = 0;
  scadaParameters_[63].max               = 0;
  // R3 за предыдущие сутки
  scadaParameters_[64].id                = -1;
  scadaParameters_[64].address           = 40086;
  scadaParameters_[64].operation         = OPERATION_READ;
  scadaParameters_[64].physic            = 0;
  scadaParameters_[64].unit              = 0;
  scadaParameters_[64].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[64].coefficient       = 0.1;
  scadaParameters_[64].min               = 0;
  scadaParameters_[64].max               = 0;
  // R4 за предыдущие сутки
  scadaParameters_[65].id                = -1;
  scadaParameters_[65].address           = 40088;
  scadaParameters_[65].operation         = OPERATION_READ;
  scadaParameters_[65].physic            = 0;
  scadaParameters_[65].unit              = 0;
  scadaParameters_[65].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[65].coefficient       = 0.1;
  scadaParameters_[65].min               = 0;
  scadaParameters_[65].max               = 0;
  // А+ за текущий месяц
  scadaParameters_[66].id                = EM_ACTIVE_PLUS_CUR_MONTH;
  scadaParameters_[66].address           = 40090;
  scadaParameters_[66].operation         = OPERATION_READ;
  scadaParameters_[66].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[66].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[66].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[66].coefficient       = 0.1;
  scadaParameters_[66].min               = 0;
  scadaParameters_[66].max               = 0;
  // А- за текущий месяц
  scadaParameters_[67].id                = EM_ACTIVE_MINUS_CUR_MONTH;
  scadaParameters_[67].address           = 40092;
  scadaParameters_[67].operation         = OPERATION_READ;
  scadaParameters_[67].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[67].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[67].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[67].coefficient       = 0.1;
  scadaParameters_[67].min               = 0;
  scadaParameters_[67].max               = 0;
  // R+ за текущий месяц
  scadaParameters_[68].id                = EM_REACTIVE_PLUS_CUR_MONTH;
  scadaParameters_[68].address           = 40094;
  scadaParameters_[68].operation         = OPERATION_READ;
  scadaParameters_[68].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[68].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[68].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[68].coefficient       = 0.1;
  scadaParameters_[68].min               = 0;
  scadaParameters_[68].max               = 0;
  // R- за текущий месяц
  scadaParameters_[69].id                = EM_REACTIVE_MINUS_CUR_MONTH;
  scadaParameters_[69].address           = 40096;
  scadaParameters_[69].operation         = OPERATION_READ;
  scadaParameters_[69].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[69].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[69].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[69].coefficient       = 0.1;
  scadaParameters_[69].min               = 0;
  scadaParameters_[69].max               = 0;
  // R1 за текущий месяц
  scadaParameters_[70].id                = -1;
  scadaParameters_[70].address           = 40098;
  scadaParameters_[70].operation         = OPERATION_READ;
  scadaParameters_[70].physic            = 0;
  scadaParameters_[70].unit              = 0;
  scadaParameters_[70].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[70].coefficient       = 0.1;
  scadaParameters_[70].min               = 0;
  scadaParameters_[70].max               = 0;
  // R2 за текущий месяц
  scadaParameters_[71].id                = -1;
  scadaParameters_[71].address           = 40100;
  scadaParameters_[71].operation         = OPERATION_READ;
  scadaParameters_[71].physic            = 0;
  scadaParameters_[71].unit              = 0;
  scadaParameters_[71].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[71].coefficient       = 0.1;
  scadaParameters_[71].min               = 0;
  scadaParameters_[71].max               = 0;
  // R3 за текущий месяц
  scadaParameters_[72].id                = -1;
  scadaParameters_[72].address           = 40102;
  scadaParameters_[72].operation         = OPERATION_READ;
  scadaParameters_[72].physic            = 0;
  scadaParameters_[72].unit              = 0;
  scadaParameters_[72].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[72].coefficient       = 0.1;
  scadaParameters_[72].min               = 0;
  scadaParameters_[72].max               = 0;
  // R4 за текущий месяц
  scadaParameters_[73].id                = -1;
  scadaParameters_[73].address           = 40104;
  scadaParameters_[73].operation         = OPERATION_READ;
  scadaParameters_[73].physic            = 0;
  scadaParameters_[73].unit              = 0;
  scadaParameters_[73].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[73].coefficient       = 0.1;
  scadaParameters_[73].min               = 0;
  scadaParameters_[73].max               = 0;
  // А+ за предыдущий месяц
  scadaParameters_[74].id                = EM_ACTIVE_PLUS_PREV_MONTH;
  scadaParameters_[74].address           = 40106;
  scadaParameters_[74].operation         = OPERATION_READ;
  scadaParameters_[74].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[74].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[74].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[74].coefficient       = 0.1;
  scadaParameters_[74].min               = 0;
  scadaParameters_[74].max               = 0;
  // А- за предыдущий месяц
  scadaParameters_[75].id                = EM_ACTIVE_MINUS_PREV_MONTH;
  scadaParameters_[75].address           = 40108;
  scadaParameters_[75].operation         = OPERATION_READ;
  scadaParameters_[75].physic            = PHYSIC_ACTIVE_ENERGY;
  scadaParameters_[75].unit              = ACTIVE_ENERGY_KW_HH;
  scadaParameters_[75].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[75].coefficient       = 0.1;
  scadaParameters_[75].min               = 0;
  scadaParameters_[75].max               = 0;
  // R+ за предыдущий месяц
  scadaParameters_[76].id                = EM_REACTIVE_PLUS_PREV_MONTH;
  scadaParameters_[76].address           = 40110;
  scadaParameters_[76].operation         = OPERATION_READ;
  scadaParameters_[76].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[76].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[76].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[76].coefficient       = 0.1;
  scadaParameters_[76].min               = 0;
  scadaParameters_[76].max               = 0;
  // R- за предыдущий месяц
  scadaParameters_[77].id                = EM_REACTIVE_MINUS_PREV_MONTH;
  scadaParameters_[77].address           = 40112;
  scadaParameters_[77].operation         = OPERATION_READ;
  scadaParameters_[77].physic            = PHYSIC_REACTIVE_ENERGY;
  scadaParameters_[77].unit              = REACTIVE_ENERGY_KVAR_HH;
  scadaParameters_[77].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[77].coefficient       = 0.1;
  scadaParameters_[77].min               = 0;
  scadaParameters_[77].max               = 0;
  // R1 за предыдущий месяц
  scadaParameters_[78].id                = -1;
  scadaParameters_[78].address           = 40114;
  scadaParameters_[78].operation         = OPERATION_READ;
  scadaParameters_[78].physic            = 0;
  scadaParameters_[78].unit              = 0;
  scadaParameters_[78].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[78].coefficient       = 0.1;
  scadaParameters_[78].min               = 0;
  scadaParameters_[78].max               = 0;
  // R2 за предыдущий месяц
  scadaParameters_[79].id                = -1;
  scadaParameters_[79].address           = 40116;
  scadaParameters_[79].operation         = OPERATION_READ;
  scadaParameters_[79].physic            = 0;
  scadaParameters_[79].unit              = 0;
  scadaParameters_[79].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[79].coefficient       = 0.1;
  scadaParameters_[79].min               = 0;
  scadaParameters_[79].max               = 0;
  // R3 за предыдущий месяц
  scadaParameters_[80].id                = -1;
  scadaParameters_[80].address           = 40118;
  scadaParameters_[80].operation         = OPERATION_READ;
  scadaParameters_[80].physic            = 0;
  scadaParameters_[80].unit              = 0;
  scadaParameters_[80].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[80].coefficient       = 0.1;
  scadaParameters_[80].min               = 0;
  scadaParameters_[80].max               = 0;
  // R4 за предыдущий месяц
  scadaParameters_[81].id                = -1;
  scadaParameters_[81].address           = 40120;
  scadaParameters_[81].operation         = OPERATION_READ;
  scadaParameters_[81].physic            = 0;
  scadaParameters_[81].unit              = 0;
  scadaParameters_[81].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[81].coefficient       = 0.1;
  scadaParameters_[81].min               = 0;
  scadaParameters_[81].max               = 0;
  // А+ за текущий год
  scadaParameters_[82].id                = -1;
  scadaParameters_[82].address           = 40122;
  scadaParameters_[82].operation         = OPERATION_READ;
  scadaParameters_[82].physic            = 0;
  scadaParameters_[82].unit              = 0;
  scadaParameters_[82].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[82].coefficient       = 0.1;
  scadaParameters_[82].min               = 0;
  scadaParameters_[82].max               = 0;
  // А- за текущий год
  scadaParameters_[83].id                = -1;
  scadaParameters_[83].address           = 40124;
  scadaParameters_[83].operation         = OPERATION_READ;
  scadaParameters_[83].physic            = 0;
  scadaParameters_[83].unit              = 0;
  scadaParameters_[83].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[83].coefficient       = 0.1;
  scadaParameters_[83].min               = 0;
  scadaParameters_[83].max               = 0;
  // R+ за текущий год
  scadaParameters_[84].id                = -1;
  scadaParameters_[84].address           = 40126;
  scadaParameters_[84].operation         = OPERATION_READ;
  scadaParameters_[84].physic            = 0;
  scadaParameters_[84].unit              = 0;
  scadaParameters_[84].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[84].coefficient       = 0.1;
  scadaParameters_[84].min               = 0;
  scadaParameters_[84].max               = 0;
  // R- за текущий год
  scadaParameters_[85].id                = -1;
  scadaParameters_[85].address           = 40128;
  scadaParameters_[85].operation         = OPERATION_READ;
  scadaParameters_[85].physic            = 0;
  scadaParameters_[85].unit              = 0;
  scadaParameters_[85].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[85].coefficient       = 0.1;
  scadaParameters_[85].min               = 0;
  scadaParameters_[85].max               = 0;
  // R1 за текущий год
  scadaParameters_[86].id                = -1;
  scadaParameters_[86].address           = 40130;
  scadaParameters_[86].operation         = OPERATION_READ;
  scadaParameters_[86].physic            = 0;
  scadaParameters_[86].unit              = 0;
  scadaParameters_[86].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[86].coefficient       = 0.1;
  scadaParameters_[86].min               = 0;
  scadaParameters_[86].max               = 0;
  // R2 за текущий год
  scadaParameters_[87].id                = -1;
  scadaParameters_[87].address           = 40132;
  scadaParameters_[87].operation         = OPERATION_READ;
  scadaParameters_[87].physic            = 0;
  scadaParameters_[87].unit              = 0;
  scadaParameters_[87].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[87].coefficient       = 0.1;
  scadaParameters_[87].min               = 0;
  scadaParameters_[87].max               = 0;
  // R3 за текущий год
  scadaParameters_[88].id                = -1;
  scadaParameters_[88].address           = 40134;
  scadaParameters_[88].operation         = OPERATION_READ;
  scadaParameters_[88].physic            = 0;
  scadaParameters_[88].unit              = 0;
  scadaParameters_[88].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[88].coefficient       = 0.1;
  scadaParameters_[88].min               = 0;
  scadaParameters_[88].max               = 0;
  // R4 за текущий год
  scadaParameters_[89].id                = -1;
  scadaParameters_[89].address           = 40136;
  scadaParameters_[89].operation         = OPERATION_READ;
  scadaParameters_[89].physic            = 0;
  scadaParameters_[89].unit              = 0;
  scadaParameters_[89].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[89].coefficient       = 0.1;
  scadaParameters_[89].min               = 0;
  scadaParameters_[89].max               = 0;
  // А+ за предыдущий год
  scadaParameters_[90].id                = -1;
  scadaParameters_[90].address           = 40138;
  scadaParameters_[90].operation         = OPERATION_READ;
  scadaParameters_[90].physic            = 0;
  scadaParameters_[90].unit              = 0;
  scadaParameters_[90].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[90].coefficient       = 0.1;
  scadaParameters_[90].min               = 0;
  scadaParameters_[90].max               = 0;
  // А- за предыдущий год
  scadaParameters_[91].id                = -1;
  scadaParameters_[91].address           = 40140;
  scadaParameters_[91].operation         = OPERATION_READ;
  scadaParameters_[91].physic            = 0;
  scadaParameters_[91].unit              = 0;
  scadaParameters_[91].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[91].coefficient       = 0.1;
  scadaParameters_[91].min               = 0;
  scadaParameters_[91].max               = 0;
  // R+ за предыдущий год
  scadaParameters_[92].id                = -1;
  scadaParameters_[92].address           = 40142;
  scadaParameters_[92].operation         = OPERATION_READ;
  scadaParameters_[92].physic            = 0;
  scadaParameters_[92].unit              = 0;
  scadaParameters_[92].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[92].coefficient       = 0.1;
  scadaParameters_[92].min               = 0;
  scadaParameters_[92].max               = 0;
  // R- за предыдущий год
  scadaParameters_[93].id                = -1;
  scadaParameters_[93].address           = 40144;
  scadaParameters_[93].operation         = OPERATION_READ;
  scadaParameters_[93].physic            = 0;
  scadaParameters_[93].unit              = 0;
  scadaParameters_[93].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[93].coefficient       = 0.1;
  scadaParameters_[93].min               = 0;
  scadaParameters_[93].max               = 0;
  // R1 за предыдущий год
  scadaParameters_[94].id                = -1;
  scadaParameters_[94].address           = 40146;
  scadaParameters_[94].operation         = OPERATION_READ;
  scadaParameters_[94].physic            = 0;
  scadaParameters_[94].unit              = 0;
  scadaParameters_[94].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[94].coefficient       = 0.1;
  scadaParameters_[94].min               = 0;
  scadaParameters_[94].max               = 0;
  // R2 за предыдущий год
  scadaParameters_[95].id                = -1;
  scadaParameters_[95].address           = 40148;
  scadaParameters_[95].operation         = OPERATION_READ;
  scadaParameters_[95].physic            = 0;
  scadaParameters_[95].unit              = 0;
  scadaParameters_[95].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[95].coefficient       = 0.1;
  scadaParameters_[95].min               = 0;
  scadaParameters_[95].max               = 0;
  // R3 за предыдущий год
  scadaParameters_[96].id                = -1;
  scadaParameters_[96].address           = 40150;
  scadaParameters_[96].operation         = OPERATION_READ;
  scadaParameters_[96].physic            = 0;
  scadaParameters_[96].unit              = 0;
  scadaParameters_[96].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[96].coefficient       = 0.1;
  scadaParameters_[96].min               = 0;
  scadaParameters_[96].max               = 0;
  // R4 за предыдущий год
  scadaParameters_[97].id                = -1;
  scadaParameters_[97].address           = 40152;
  scadaParameters_[97].operation         = OPERATION_READ;
  scadaParameters_[97].physic            = 0;
  scadaParameters_[97].unit              = 0;
  scadaParameters_[97].typeData          = TYPE_DATA_UINT32;
  scadaParameters_[97].coefficient       = 0.1;
  scadaParameters_[97].min               = 0;
  scadaParameters_[97].max               = 0;
  // Номинальное напряжение сети
  scadaParameters_[98].id                = CCS_TRANS_NOMINAL_VOLTAGE_INPUT;
  scadaParameters_[98].address           = 30000;
  scadaParameters_[98].operation         = OPERATION_WRITE;
  scadaParameters_[98].physic            = PHYSIC_VOLTAGE;
  scadaParameters_[98].unit              = VOLTAGE_V;
  scadaParameters_[98].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[98].coefficient       = 1;
  scadaParameters_[98].min               = 100;
  scadaParameters_[98].max               = 600;
  // Высокое напряжение
  scadaParameters_[99].id                = CCS_PROT_SUPPLY_OVERVOLTAGE_MODE;
  scadaParameters_[99].address           = 30001;
  scadaParameters_[99].operation         = OPERATION_WRITE;
  scadaParameters_[99].physic            = PHYSIC_NUMERIC;
  scadaParameters_[99].unit              = 0;
  scadaParameters_[99].typeData          = TYPE_DATA_UINT16;
  scadaParameters_[99].coefficient       = 1;
  scadaParameters_[99].min               = 0;
  scadaParameters_[99].max               = 2;
  // Уставка высокого напряжения фазы
  scadaParameters_[100].id               = CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_SETPOINT;
  scadaParameters_[100].address          = 30002;
  scadaParameters_[100].operation        = OPERATION_WRITE;
  scadaParameters_[100].physic           = PHYSIC_PERCENT;
  scadaParameters_[100].unit             = PERCENT_PERCENT;
  scadaParameters_[100].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[100].coefficient      = 1;
  scadaParameters_[100].min              = 0;
  scadaParameters_[100].max              = 150;
  // Задержка срабатывания уставка
  scadaParameters_[101].id               = CCS_PROT_SUPPLY_OVERVOLTAGE_TRIP_DELAY;
  scadaParameters_[101].address          = 30003;
  scadaParameters_[101].operation        = OPERATION_WRITE;
  scadaParameters_[101].physic           = PHYSIC_TIME;
  scadaParameters_[101].unit             = TIME_SS;
  scadaParameters_[101].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[101].coefficient      = 1;
  scadaParameters_[101].min              = 0;
  scadaParameters_[101].max              = 600;
  // Задержка активации уставка
  scadaParameters_[102].id               = CCS_PROT_SUPPLY_OVERVOLTAGE_ACTIV_DELAY;
  scadaParameters_[102].address          = 30004;
  scadaParameters_[102].operation        = OPERATION_WRITE;
  scadaParameters_[102].physic           = PHYSIC_TIME;
  scadaParameters_[102].unit             = TIME_SS;
  scadaParameters_[102].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[102].coefficient      = 1;
  scadaParameters_[102].min              = 0;
  scadaParameters_[102].max              = 59999;
  // Низкое напряжение
  scadaParameters_[103].id               = CCS_PROT_SUPPLY_UNDERVOLTAGE_MODE;
  scadaParameters_[103].address          = 30005;
  scadaParameters_[103].operation        = OPERATION_WRITE;
  scadaParameters_[103].physic           = PHYSIC_NUMERIC;
  scadaParameters_[103].unit             = 0;
  scadaParameters_[103].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[103].coefficient      = 1;
  scadaParameters_[103].min              = 0;
  scadaParameters_[103].max              = 2;
  // Уставка низкого напряжения фазы
  scadaParameters_[104].id               = CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_SETPOINT;
  scadaParameters_[104].address          = 30006;
  scadaParameters_[104].operation        = OPERATION_WRITE;
  scadaParameters_[104].physic           = PHYSIC_PERCENT;
  scadaParameters_[104].unit             = PERCENT_PERCENT;
  scadaParameters_[104].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[104].coefficient      = 1;
  scadaParameters_[104].min              = 0;
  scadaParameters_[104].max              = 100;
  // Задержка срабатывания уставка
  scadaParameters_[105].id               = CCS_PROT_SUPPLY_UNDERVOLTAGE_TRIP_DELAY;
  scadaParameters_[105].address          = 30007;
  scadaParameters_[105].operation        = OPERATION_WRITE;
  scadaParameters_[105].physic           = PHYSIC_TIME;
  scadaParameters_[105].unit             = TIME_SS;
  scadaParameters_[105].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[105].coefficient      = 1;
  scadaParameters_[105].min              = 0;
  scadaParameters_[105].max              = 600;
  // Задержка активации уставка
  scadaParameters_[106].id               = CCS_PROT_SUPPLY_UNDERVOLTAGE_ACTIV_DELAY;
  scadaParameters_[106].address          = 30008;
  scadaParameters_[106].operation        = OPERATION_WRITE;
  scadaParameters_[106].physic           = PHYSIC_TIME;
  scadaParameters_[106].unit             = TIME_SS;
  scadaParameters_[106].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[106].coefficient      = 1;
  scadaParameters_[106].min              = 0;
  scadaParameters_[106].max              = 59999;
  // Дисбаланс напряжения
  scadaParameters_[107].id               = CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_MODE;
  scadaParameters_[107].address          = 30009;
  scadaParameters_[107].operation        = OPERATION_WRITE;
  scadaParameters_[107].physic           = PHYSIC_NUMERIC;
  scadaParameters_[107].unit             = 0;
  scadaParameters_[107].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[107].coefficient      = 1;
  scadaParameters_[107].min              = 0;
  scadaParameters_[107].max              = 2;
  // Уставка дисбаланса напряжений
  scadaParameters_[108].id               = CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_SETPOINT;
  scadaParameters_[108].address          = 30010;
  scadaParameters_[108].operation        = OPERATION_WRITE;
  scadaParameters_[108].physic           = PHYSIC_PERCENT;
  scadaParameters_[108].unit             = PERCENT_PERCENT;
  scadaParameters_[108].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[108].coefficient      = 1;
  scadaParameters_[108].min              = 0;
  scadaParameters_[108].max              = 200;
  // Задержка срабатывания уставка
  scadaParameters_[109].id               = CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_TRIP_DELAY;
  scadaParameters_[109].address          = 30011;
  scadaParameters_[109].operation        = OPERATION_WRITE;
  scadaParameters_[109].physic           = PHYSIC_TIME;
  scadaParameters_[109].unit             = TIME_SS;
  scadaParameters_[109].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[109].coefficient      = 1;
  scadaParameters_[109].min              = 0;
  scadaParameters_[109].max              = 600;
  // Задержка активации уставка
  scadaParameters_[110].id               = CCS_PROT_SUPPLY_IMBALANCE_VOLTAGE_ACTIV_DELAY;
  scadaParameters_[110].address          = 30012;
  scadaParameters_[110].operation        = OPERATION_WRITE;
  scadaParameters_[110].physic           = PHYSIC_TIME;
  scadaParameters_[110].unit             = TIME_SS;
  scadaParameters_[110].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[110].coefficient      = 1;
  scadaParameters_[110].min              = 0;
  scadaParameters_[110].max              = 59999;
  // Время АПВ защит по напряжению (Автозапуск)
  scadaParameters_[111].id               = CCS_PROT_SUPPLY_RESTART_DELAY;
  scadaParameters_[111].address          = 30013;
  scadaParameters_[111].operation        = OPERATION_WRITE;
  scadaParameters_[111].physic           = PHYSIC_TIME;
  scadaParameters_[111].unit             = TIME_SS;
  scadaParameters_[111].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[111].coefficient      = 1;
  scadaParameters_[111].min              = 1;
  scadaParameters_[111].max              = 59999;
  // Номинальный ток ПЭД
  scadaParameters_[112].id               = VSD_MOTOR_CURRENT;
  scadaParameters_[112].address          = 30014;
  scadaParameters_[112].operation        = OPERATION_WRITE;
  scadaParameters_[112].physic           = PHYSIC_CURRENT;
  scadaParameters_[112].unit             = CURRENT_A;
  scadaParameters_[112].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[112].coefficient      = 0.1;
  scadaParameters_[112].min              = 0;
  scadaParameters_[112].max              = 65535;
  // Номинальный коэффициент мощности
  scadaParameters_[113].id               = VSD_MOTOR_COS_PHI;
  scadaParameters_[113].address          = 30015;
  scadaParameters_[113].operation        = OPERATION_WRITE;
  scadaParameters_[113].physic           = PHYSIC_NUMERIC;
  scadaParameters_[113].unit             = 0;
  scadaParameters_[113].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[113].coefficient      = 0.01;
  scadaParameters_[113].min              = 0;
  scadaParameters_[113].max              = 65535;
  // Напряж. Отпайки ТМПН
  scadaParameters_[114].id               = CCS_TRANS_VOLTAGE_TAP_OFF;
  scadaParameters_[114].address          = 30016;
  scadaParameters_[114].operation        = OPERATION_WRITE;
  scadaParameters_[114].physic           = PHYSIC_VOLTAGE;
  scadaParameters_[114].unit             = VOLTAGE_V;
  scadaParameters_[114].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[114].coefficient      = 1;
  scadaParameters_[114].min              = 380;
  scadaParameters_[114].max              = 65535;
  // Перегруз (ЗП)
  scadaParameters_[115].id               = CCS_PROT_MOTOR_OVERLOAD_MODE;
  scadaParameters_[115].address          = 30017;
  scadaParameters_[115].operation        = OPERATION_WRITE;
  scadaParameters_[115].physic           = PHYSIC_NUMERIC;
  scadaParameters_[115].unit             = 0;
  scadaParameters_[115].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[115].coefficient      = 1;
  scadaParameters_[115].min              = 0;
  scadaParameters_[115].max              = 2;
  // Уставка перегрузки
  scadaParameters_[116].id               = CCS_PROT_MOTOR_OVERLOAD_TRIP_SETPOINT;
  scadaParameters_[116].address          = 30018;
  scadaParameters_[116].operation        = OPERATION_WRITE;
  scadaParameters_[116].physic           = PHYSIC_PERCENT;
  scadaParameters_[116].unit             = PERCENT_PERCENT;
  scadaParameters_[116].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[116].coefficient      = 1;
  scadaParameters_[116].min              = 0;
  scadaParameters_[116].max              = 150;
  // Задержка срабатывания уставка
  scadaParameters_[117].id               = CCS_PROT_MOTOR_OVERLOAD_TRIP_DELAY;
  scadaParameters_[117].address          = 30019;
  scadaParameters_[117].operation        = OPERATION_WRITE;
  scadaParameters_[117].physic           = PHYSIC_TIME;
  scadaParameters_[117].unit             = TIME_SS;
  scadaParameters_[117].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[117].coefficient      = 1;
  scadaParameters_[117].min              = 0;
  scadaParameters_[117].max              = 600;
  // Задержка активации уставка
  scadaParameters_[118].id               = CCS_PROT_MOTOR_OVERLOAD_ACTIV_DELAY;
  scadaParameters_[118].address          = 30020;
  scadaParameters_[118].operation        = OPERATION_WRITE;
  scadaParameters_[118].physic           = PHYSIC_TIME;
  scadaParameters_[118].unit             = TIME_SS;
  scadaParameters_[118].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[118].coefficient      = 1;
  scadaParameters_[118].min              = 0;
  scadaParameters_[118].max              = 59999;
  // Задержка АПВ уставка
  scadaParameters_[119].id               = CCS_PROT_MOTOR_OVERLOAD_RESTART_DELAY;
  scadaParameters_[119].address          = 30021;
  scadaParameters_[119].operation        = OPERATION_WRITE;
  scadaParameters_[119].physic           = PHYSIC_TIME;
  scadaParameters_[119].unit             = TIME_MM;
  scadaParameters_[119].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[119].coefficient      = 1;
  scadaParameters_[119].min              = 1;
  scadaParameters_[119].max              = 59999;
  // Недогруз (ЗСП)
  scadaParameters_[120].id               = CCS_PROT_MOTOR_UNDERLOAD_MODE;
  scadaParameters_[120].address          = 30022;
  scadaParameters_[120].operation        = OPERATION_WRITE;
  scadaParameters_[120].physic           = PHYSIC_NUMERIC;
  scadaParameters_[120].unit             = 0;
  scadaParameters_[120].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[120].coefficient      = 1;
  scadaParameters_[120].min              = 0;
  scadaParameters_[120].max              = 2;
  // Уставка недогрузки
  scadaParameters_[121].id               = CCS_PROT_MOTOR_UNDERLOAD_TRIP_SETPOINT;
  scadaParameters_[121].address          = 30023;
  scadaParameters_[121].operation        = OPERATION_WRITE;
  scadaParameters_[121].physic           = PHYSIC_PERCENT;
  scadaParameters_[121].unit             = PERCENT_PERCENT;
  scadaParameters_[121].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[121].coefficient      = 1;
  scadaParameters_[121].min              = 0;
  scadaParameters_[121].max              = 100;
  // Задержка срабатывания уставка
  scadaParameters_[122].id               = CCS_PROT_MOTOR_UNDERLOAD_TRIP_DELAY;
  scadaParameters_[122].address          = 30024;
  scadaParameters_[122].operation        = OPERATION_WRITE;
  scadaParameters_[122].physic           = PHYSIC_TIME;
  scadaParameters_[122].unit             = TIME_SS;
  scadaParameters_[122].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[122].coefficient      = 1;
  scadaParameters_[122].min              = 0;
  scadaParameters_[122].max              = 600;
  // Задержка активации уставка
  scadaParameters_[123].id               = CCS_PROT_MOTOR_UNDERLOAD_ACTIV_DELAY;
  scadaParameters_[123].address          = 30025;
  scadaParameters_[123].operation        = OPERATION_WRITE;
  scadaParameters_[123].physic           = PHYSIC_TIME;
  scadaParameters_[123].unit             = TIME_SS;
  scadaParameters_[123].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[123].coefficient      = 1;
  scadaParameters_[123].min              = 0;
  scadaParameters_[123].max              = 59999;
  // Задержка АПВ уставка
  scadaParameters_[124].id               = CCS_PROT_MOTOR_UNDERLOAD_RESTART_DELAY;
  scadaParameters_[124].address          = 30026;
  scadaParameters_[124].operation        = OPERATION_WRITE;
  scadaParameters_[124].physic           = PHYSIC_TIME;
  scadaParameters_[124].unit             = TIME_MM;
  scadaParameters_[124].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[124].coefficient      = 1;
  scadaParameters_[124].min              = 1;
  scadaParameters_[124].max              = 59999;
  // Дисбаланс тока
  scadaParameters_[125].id               = CCS_PROT_MOTOR_IMBALANCE_CURRENT_MODE;
  scadaParameters_[125].address          = 30027;
  scadaParameters_[125].operation        = OPERATION_WRITE;
  scadaParameters_[125].physic           = PHYSIC_NUMERIC;
  scadaParameters_[125].unit             = 0;
  scadaParameters_[125].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[125].coefficient      = 1;
  scadaParameters_[125].min              = 0;
  scadaParameters_[125].max              = 2;
  // Дисбаланс тока, уставка
  scadaParameters_[126].id               = CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_SETPOINT;
  scadaParameters_[126].address          = 30028;
  scadaParameters_[126].operation        = OPERATION_WRITE;
  scadaParameters_[126].physic           = PHYSIC_PERCENT;
  scadaParameters_[126].unit             = PERCENT_PERCENT;
  scadaParameters_[126].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[126].coefficient      = 1;
  scadaParameters_[126].min              = 1;
  scadaParameters_[126].max              = 100;
  // Дисбаланс тока, задержка отключения
  scadaParameters_[127].id               = CCS_PROT_MOTOR_IMBALANCE_CURRENT_TRIP_DELAY;
  scadaParameters_[127].address          = 30029;
  scadaParameters_[127].operation        = OPERATION_WRITE;
  scadaParameters_[127].physic           = PHYSIC_TIME;
  scadaParameters_[127].unit             = TIME_SS;
  scadaParameters_[127].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[127].coefficient      = 1;
  scadaParameters_[127].min              = 0;
  scadaParameters_[127].max              = 600;
  // Дисбаланс тока, пусковое время
  scadaParameters_[128].id               = CCS_PROT_MOTOR_IMBALANCE_CURRENT_ACTIV_DELAY;
  scadaParameters_[128].address          = 30030;
  scadaParameters_[128].operation        = OPERATION_WRITE;
  scadaParameters_[128].physic           = PHYSIC_TIME;
  scadaParameters_[128].unit             = TIME_SS;
  scadaParameters_[128].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[128].coefficient      = 1;
  scadaParameters_[128].min              = 0;
  scadaParameters_[128].max              = 59999;
  // Дисбаланс тока, задержка АПВ
  scadaParameters_[129].id               = CCS_PROT_MOTOR_IMBALANCE_CURRENT_RESTART_DELAY;
  scadaParameters_[129].address          = 30031;
  scadaParameters_[129].operation        = OPERATION_WRITE;
  scadaParameters_[129].physic           = PHYSIC_TIME;
  scadaParameters_[129].unit             = TIME_MM;
  scadaParameters_[129].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[129].coefficient      = 1;
  scadaParameters_[129].min              = 0;
  scadaParameters_[129].max              = 59999;
  // Сопротивление изоляции
  scadaParameters_[130].id               = CCS_PROT_DHS_RESISTANCE_MODE;
  scadaParameters_[130].address          = 30032;
  scadaParameters_[130].operation        = OPERATION_WRITE;
  scadaParameters_[130].physic           = PHYSIC_NUMERIC;
  scadaParameters_[130].unit             = 0;
  scadaParameters_[130].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[130].coefficient      = 1;
  scadaParameters_[130].min              = 0;
  scadaParameters_[130].max              = 1;
  // Минимальное сопротивление изоляции
  scadaParameters_[131].id               = CCS_PROT_DHS_RESISTANCE_TRIP_SETPOINT;
  scadaParameters_[131].address          = 30033;
  scadaParameters_[131].operation        = OPERATION_WRITE;
  scadaParameters_[131].physic           = PHYSIC_RESISTANCE;
  scadaParameters_[131].unit             = RESISTANCE_KOM;
  scadaParameters_[131].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[131].coefficient      = 1;
  scadaParameters_[131].min              = 30;
  scadaParameters_[131].max              = 9999;
  // Турбинное вращение
  scadaParameters_[132].id               = CCS_PROT_MOTOR_ASYNC_MODE;
  scadaParameters_[132].address          = 30034;
  scadaParameters_[132].operation        = OPERATION_WRITE;
  scadaParameters_[132].physic           = PHYSIC_NUMERIC;
  scadaParameters_[132].unit             = 0;
  scadaParameters_[132].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[132].coefficient      = 1;
  scadaParameters_[132].min              = 0;
  scadaParameters_[132].max              = 1;
  // Турбин.вращение уст.
  scadaParameters_[133].id               = CCS_PROT_MOTOR_ASYNC_TRIP_SETPOINT;
  scadaParameters_[133].address          = 30035;
  scadaParameters_[133].operation        = OPERATION_WRITE;
  scadaParameters_[133].physic           = PHYSIC_FREQUENCY;
  scadaParameters_[133].unit             = FREQUENCY_HZ;
  scadaParameters_[133].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[133].coefficient      = 1;
  scadaParameters_[133].min              = 1;
  scadaParameters_[133].max              = 255;
  // Электрическая блокировка силового отсека
  scadaParameters_[134].id               = CCS_PROT_OTHER_LOCK_DOOR_MODE;
  scadaParameters_[134].address          = 30036;
  scadaParameters_[134].operation        = OPERATION_WRITE;
  scadaParameters_[134].physic           = PHYSIC_NUMERIC;
  scadaParameters_[134].unit             = 0;
  scadaParameters_[134].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[134].coefficient      = 1;
  scadaParameters_[134].min              = 0;
  scadaParameters_[134].max              = 1;
  // Недогруз (ЗСП). Количество разрешенных АПВ
  scadaParameters_[135].id               = CCS_PROT_MOTOR_UNDERLOAD_RESTART_LIMIT;
  scadaParameters_[135].address          = 30037;
  scadaParameters_[135].operation        = OPERATION_WRITE;
  scadaParameters_[135].physic           = PHYSIC_NUMERIC;
  scadaParameters_[135].unit             = 0;
  scadaParameters_[135].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[135].coefficient      = 1;
  scadaParameters_[135].min              = 0;
  scadaParameters_[135].max              = 1000;
  // Перегруз (ЗП). Количество разрешенных АПВ
  scadaParameters_[136].id               = CCS_PROT_MOTOR_OVERLOAD_RESTART_LIMIT;
  scadaParameters_[136].address          = 30038;
  scadaParameters_[136].operation        = OPERATION_WRITE;
  scadaParameters_[136].physic           = PHYSIC_NUMERIC;
  scadaParameters_[136].unit             = 0;
  scadaParameters_[136].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[136].coefficient      = 1;
  scadaParameters_[136].min              = 0;
  scadaParameters_[136].max              = 1000;
  // Кол-во разрешенных АПВ после других защит
  scadaParameters_[137].id               = CCS_PROT_OTHER_RESTART_LIMIT;
  scadaParameters_[137].address          = 30039;
  scadaParameters_[137].operation        = OPERATION_WRITE;
  scadaParameters_[137].physic           = PHYSIC_NUMERIC;
  scadaParameters_[137].unit             = 0;
  scadaParameters_[137].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[137].coefficient      = 1;
  scadaParameters_[137].min              = 1;
  scadaParameters_[137].max              = 200;
  // Периодический режим работы
  scadaParameters_[138].id               = CCS_RGM_PERIODIC_MODE;
  scadaParameters_[138].address          = 30040;
  scadaParameters_[138].operation        = OPERATION_WRITE;
  scadaParameters_[138].physic           = PHYSIC_NUMERIC;
  scadaParameters_[138].unit             = 0;
  scadaParameters_[138].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[138].coefficient      = 1;
  scadaParameters_[138].min              = 0;
  scadaParameters_[138].max              = 1;
  // Период работы по программе
  scadaParameters_[139].id               = CCS_RGM_PERIODIC_RUN_PERIOD;
  scadaParameters_[139].address          = 30041;
  scadaParameters_[139].operation        = OPERATION_WRITE;
  scadaParameters_[139].physic           = PHYSIC_TIME;
  scadaParameters_[139].unit             = TIME_MM;
  scadaParameters_[139].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[139].coefficient      = 1;
  scadaParameters_[139].min              = 1;
  scadaParameters_[139].max              = 59999;
  // Период паузы по программе
  scadaParameters_[140].id               = CCS_RGM_PERIODIC_STOP_PERIOD;
  scadaParameters_[140].address          = 30042;
  scadaParameters_[140].operation        = OPERATION_WRITE;
  scadaParameters_[140].physic           = PHYSIC_TIME;
  scadaParameters_[140].unit             = TIME_MM;
  scadaParameters_[140].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[140].coefficient      = 1;
  scadaParameters_[140].min              = 1;
  scadaParameters_[140].max              = 59999;
  // Резерв
  scadaParameters_[141].id               = -1;
  scadaParameters_[141].address          = 30043;
  scadaParameters_[141].operation        = OPERATION_WRITE;
  scadaParameters_[141].physic           = 0;
  scadaParameters_[141].unit             = 0;
  scadaParameters_[141].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[141].coefficient      = 1;
  scadaParameters_[141].min              = 0;
  scadaParameters_[141].max              = 0;
  // Режим работы ПЧ
  scadaParameters_[142].id               = -1;
  scadaParameters_[142].address          = 30044;
  scadaParameters_[142].operation        = OPERATION_WRITE;
  scadaParameters_[142].physic           = 0;
  scadaParameters_[142].unit             = 0;
  scadaParameters_[142].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[142].coefficient      = 1;
  scadaParameters_[142].min              = 0;
  scadaParameters_[142].max              = 0;
  // Уставка частоты
  scadaParameters_[143].id               = VSD_FREQUENCY;
  scadaParameters_[143].address          = 30045;
  scadaParameters_[143].operation        = OPERATION_WRITE;
  scadaParameters_[143].physic           = PHYSIC_FREQUENCY;
  scadaParameters_[143].unit             = FREQUENCY_HZ;
  scadaParameters_[143].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[143].coefficient      = 0.01;
  scadaParameters_[143].min              = 0;
  scadaParameters_[143].max              = 20000;
  // Поддерживаемый ток двигателя, уставка
  scadaParameters_[144].id               = -1;
  scadaParameters_[144].address          = 30046;
  scadaParameters_[144].operation        = OPERATION_WRITE;
  scadaParameters_[144].physic           = 0;
  scadaParameters_[144].unit             = 0;
  scadaParameters_[144].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[144].coefficient      = 1;
  scadaParameters_[144].min              = 0;
  scadaParameters_[144].max              = 0;
  // Значение поддерживаемого параметра, уставка
  scadaParameters_[145].id               = -1;
  scadaParameters_[145].address          = 30047;
  scadaParameters_[145].operation        = OPERATION_WRITE;
  scadaParameters_[145].physic           = 0;
  scadaParameters_[145].unit             = 0;
  scadaParameters_[145].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[145].coefficient      = 1;
  scadaParameters_[145].min              = 0;
  scadaParameters_[145].max              = 0;
  // Время разгона
  scadaParameters_[146].id               = VSD_T_SPEEDUP;
  scadaParameters_[146].address          = 30048;
  scadaParameters_[146].operation        = OPERATION_WRITE;
  scadaParameters_[146].physic           = PHYSIC_TIME;
  scadaParameters_[146].unit             = TIME_SS;
  scadaParameters_[146].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[146].coefficient      = 0.1;
  scadaParameters_[146].min              = 0;
  scadaParameters_[146].max              = 6000;
  // Время замедления
  scadaParameters_[147].id               = VSD_T_SPEEDDOWN;
  scadaParameters_[147].address          = 30049;
  scadaParameters_[147].operation        = OPERATION_WRITE;
  scadaParameters_[147].physic           = PHYSIC_TIME;
  scadaParameters_[147].unit             = TIME_SS;
  scadaParameters_[147].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[147].coefficient      = 0.1;
  scadaParameters_[147].min              = 0;
  scadaParameters_[147].max              = 6000;
  // Темп разгона
  scadaParameters_[148].id               = VSD_TEMP_SPEEDUP;
  scadaParameters_[148].address          = 30050;
  scadaParameters_[148].operation        = OPERATION_WRITE;
  scadaParameters_[148].physic           = PHYSIC_TEMP;
  scadaParameters_[148].unit             = TEMP_HZ_SS;
  scadaParameters_[148].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[148].coefficient      = 0.01;
  scadaParameters_[148].min              = 0;
  scadaParameters_[148].max              = 8000;
  // Минимальная частота
  scadaParameters_[149].id               = -1;
  scadaParameters_[149].address          = 30051;
  scadaParameters_[149].operation        = OPERATION_WRITE;
  scadaParameters_[149].physic           = 0;
  scadaParameters_[149].unit             = 0;
  scadaParameters_[149].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[149].coefficient      = 1;
  scadaParameters_[149].min              = 0;
  scadaParameters_[149].max              = 2;
  // Уставка минимального значения частоты
  scadaParameters_[150].id               = VSD_LOW_LIM_SPEED_MOTOR;
  scadaParameters_[150].address          = 30052;
  scadaParameters_[150].operation        = OPERATION_WRITE;
  scadaParameters_[150].physic           = PHYSIC_FREQUENCY;
  scadaParameters_[150].unit             = FREQUENCY_HZ;
  scadaParameters_[150].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[150].coefficient      = 0.01;
  scadaParameters_[150].min              = 0;
  scadaParameters_[150].max              = 20000;
  // Минимальная частота, задержка отключения
  scadaParameters_[151].id               = -1;
  scadaParameters_[151].address          = 30053;
  scadaParameters_[151].operation        = OPERATION_WRITE;
  scadaParameters_[151].physic           = 0;
  scadaParameters_[151].unit             = 0;
  scadaParameters_[151].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[151].coefficient      = 1;
  scadaParameters_[151].min              = 0;
  scadaParameters_[151].max              = 600;
  // Минимальная частота, пусковое время
  scadaParameters_[152].id               = -1;
  scadaParameters_[152].address          = 30054;
  scadaParameters_[152].operation        = OPERATION_WRITE;
  scadaParameters_[152].physic           = 0;
  scadaParameters_[152].unit             = 0;
  scadaParameters_[152].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[152].coefficient      = 1;
  scadaParameters_[152].min              = 0;
  scadaParameters_[152].max              = 9999;
  // Минимальная частота, задержка АПВ
  scadaParameters_[153].id               = -1;
  scadaParameters_[153].address          = 30055;
  scadaParameters_[153].operation        = OPERATION_WRITE;
  scadaParameters_[153].physic           = 0;
  scadaParameters_[153].unit             = 0;
  scadaParameters_[153].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[153].coefficient      = 1;
  scadaParameters_[153].min              = 0;
  scadaParameters_[153].max              = 9999;
  // Максимальная частота
  scadaParameters_[154].id               = -1;
  scadaParameters_[154].address          = 30056;
  scadaParameters_[154].operation        = OPERATION_WRITE;
  scadaParameters_[154].physic           = 0;
  scadaParameters_[154].unit             = 0;
  scadaParameters_[154].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[154].coefficient      = 1;
  scadaParameters_[154].min              = 0;
  scadaParameters_[154].max              = 2;
  // Уставка максимального значения частоты
  scadaParameters_[155].id               = VSD_HIGH_LIM_SPEED_MOTOR;
  scadaParameters_[155].address          = 30057;
  scadaParameters_[155].operation        = OPERATION_WRITE;
  scadaParameters_[155].physic           = PHYSIC_FREQUENCY;
  scadaParameters_[155].unit             = FREQUENCY_HZ;
  scadaParameters_[155].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[155].coefficient      = 0.01;
  scadaParameters_[155].min              = 0;
  scadaParameters_[155].max              = 20000;
  // Максимальная частота, задержка отключения
  scadaParameters_[156].id               = -1;
  scadaParameters_[156].address          = 30058;
  scadaParameters_[156].operation        = OPERATION_WRITE;
  scadaParameters_[156].physic           = 0;
  scadaParameters_[156].unit             = 0;
  scadaParameters_[156].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[156].coefficient      = 1;
  scadaParameters_[156].min              = 0;
  scadaParameters_[156].max              = 0;
  // Максимальная частота, пусковое время
  scadaParameters_[157].id               = -1;
  scadaParameters_[157].address          = 30059;
  scadaParameters_[157].operation        = OPERATION_WRITE;
  scadaParameters_[157].physic           = 0;
  scadaParameters_[157].unit             = 0;
  scadaParameters_[157].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[157].coefficient      = 1;
  scadaParameters_[157].min              = 0;
  scadaParameters_[157].max              = 0;
  // Максимальная частота, задержка АПВ
  scadaParameters_[158].id               = -1;
  scadaParameters_[158].address          = 30060;
  scadaParameters_[158].operation        = OPERATION_WRITE;
  scadaParameters_[158].physic           = 0;
  scadaParameters_[158].unit             = 0;
  scadaParameters_[158].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[158].coefficient      = 1;
  scadaParameters_[158].min              = 0;
  scadaParameters_[158].max              = 0;
  // Нагрузка на шток
  scadaParameters_[159].id               = -1;
  scadaParameters_[159].address          = 30061;
  scadaParameters_[159].operation        = OPERATION_WRITE;
  scadaParameters_[159].physic           = 0;
  scadaParameters_[159].unit             = 0;
  scadaParameters_[159].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[159].coefficient      = 1;
  scadaParameters_[159].min              = 0;
  scadaParameters_[159].max              = 0;
  // Нагрузка на шток, минимальная уставка
  scadaParameters_[160].id               = -1;
  scadaParameters_[160].address          = 30062;
  scadaParameters_[160].operation        = OPERATION_WRITE;
  scadaParameters_[160].physic           = 0;
  scadaParameters_[160].unit             = 0;
  scadaParameters_[160].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[160].coefficient      = 1;
  scadaParameters_[160].min              = 0;
  scadaParameters_[160].max              = 0;
  // Нагрузка на шток, максимальная уставка
  scadaParameters_[161].id               = -1;
  scadaParameters_[161].address          = 30063;
  scadaParameters_[161].operation        = OPERATION_WRITE;
  scadaParameters_[161].physic           = 0;
  scadaParameters_[161].unit             = 0;
  scadaParameters_[161].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[161].coefficient      = 1;
  scadaParameters_[161].min              = 0;
  scadaParameters_[161].max              = 0;
  // Нагрузка на шток, задержка отключения
  scadaParameters_[162].id               = -1;
  scadaParameters_[162].address          = 30064;
  scadaParameters_[162].operation        = OPERATION_WRITE;
  scadaParameters_[162].physic           = 0;
  scadaParameters_[162].unit             = 0;
  scadaParameters_[162].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[162].coefficient      = 1;
  scadaParameters_[162].min              = 0;
  scadaParameters_[162].max              = 0;
  // Нагрузка на шток, пусковое время
  scadaParameters_[163].id               = -1;
  scadaParameters_[163].address          = 30065;
  scadaParameters_[163].operation        = OPERATION_WRITE;
  scadaParameters_[163].physic           = 0;
  scadaParameters_[163].unit             = 0;
  scadaParameters_[163].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[163].coefficient      = 1;
  scadaParameters_[163].min              = 0;
  scadaParameters_[163].max              = 0;
  // Нагрузка на шток, задержка АПВ
  scadaParameters_[164].id               = -1;
  scadaParameters_[164].address          = 30066;
  scadaParameters_[164].operation        = OPERATION_WRITE;
  scadaParameters_[164].physic           = 0;
  scadaParameters_[164].unit             = 0;
  scadaParameters_[164].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[164].coefficient      = 1;
  scadaParameters_[164].min              = 0;
  scadaParameters_[164].max              = 0;
  // Номер месторождения
  scadaParameters_[165].id               = CCS_NUMBER_CDNG;
  scadaParameters_[165].address          = 30067;
  scadaParameters_[165].operation        = OPERATION_WRITE;
  scadaParameters_[165].physic           = PHYSIC_NUMERIC;
  scadaParameters_[165].unit             = 0;
  scadaParameters_[165].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[165].coefficient      = 1;
  scadaParameters_[165].min              = 0;
  scadaParameters_[165].max              = 65535;
  // Номер куста
  scadaParameters_[166].id               = CCS_NUMBER_BUSH;
  scadaParameters_[166].address          = 30068;
  scadaParameters_[166].operation        = OPERATION_WRITE;
  scadaParameters_[166].physic           = PHYSIC_NUMERIC;
  scadaParameters_[166].unit             = 0;
  scadaParameters_[166].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[166].coefficient      = 1;
  scadaParameters_[166].min              = 0;
  scadaParameters_[166].max              = 65535;
  // Номер скважины
  scadaParameters_[167].id               = CCS_NUMBER_WELL;
  scadaParameters_[167].address          = 30069;
  scadaParameters_[167].operation        = OPERATION_WRITE;
  scadaParameters_[167].physic           = PHYSIC_NUMERIC;
  scadaParameters_[167].unit             = 0;
  scadaParameters_[167].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[167].coefficient      = 1;
  scadaParameters_[167].min              = 0;
  scadaParameters_[167].max              = 65535;
  // Мощн. Двигателя
  scadaParameters_[168].id               = VSD_MOTOR_POWER;
  scadaParameters_[168].address          = 30070;
  scadaParameters_[168].operation        = OPERATION_WRITE;
  scadaParameters_[168].physic           = PHYSIC_POWER;
  scadaParameters_[168].unit             = POWER_KW;
  scadaParameters_[168].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[168].coefficient      = 0.1;
  scadaParameters_[168].min              = 0;
  scadaParameters_[168].max              = 65535;
  // Производительность насоса
  scadaParameters_[169].id               = CCS_PUMP_CAPACITY;
  scadaParameters_[169].address          = 30071;
  scadaParameters_[169].operation        = OPERATION_WRITE;
  scadaParameters_[169].physic           = PHYSIC_FLOW;
  scadaParameters_[169].unit             = FLOW_M3_DD;
  scadaParameters_[169].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[169].coefficient      = 1;
  scadaParameters_[169].min              = 0;
  scadaParameters_[169].max              = 2000;
  // Напор насоса
  scadaParameters_[170].id               = CCS_PUMP_HEAD;
  scadaParameters_[170].address          = 30072;
  scadaParameters_[170].operation        = OPERATION_WRITE;
  scadaParameters_[170].physic           = PHYSIC_LENGHT;
  scadaParameters_[170].unit             = LENGTH_M;
  scadaParameters_[170].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[170].coefficient      = 1;
  scadaParameters_[170].min              = 0;
  scadaParameters_[170].max              = 9999;
  // Глубина спуска
  scadaParameters_[171].id               = CCS_DEPTH;
  scadaParameters_[171].address          = 30073;
  scadaParameters_[171].operation        = OPERATION_WRITE;
  scadaParameters_[171].physic           = PHYSIC_LENGHT;
  scadaParameters_[171].unit             = LENGTH_M;
  scadaParameters_[171].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[171].coefficient      = 1;
  scadaParameters_[171].min              = 0;
  scadaParameters_[171].max              = 9999;
  // Диаметр НКТ
  scadaParameters_[172].id               = -1;
  scadaParameters_[172].address          = 30074;
  scadaParameters_[172].operation        = OPERATION_WRITE;
  scadaParameters_[172].physic           = PHYSIC_LENGHT;
  scadaParameters_[172].unit             = LENGTH_M;
  scadaParameters_[172].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[172].coefficient      = 0.001;
  scadaParameters_[172].min              = 0;
  scadaParameters_[172].max              = 9999000;
  // Дата
  scadaParameters_[173].id               = 0;
  scadaParameters_[173].address          = 30075;
  scadaParameters_[173].operation        = OPERATION_WRITE;
  scadaParameters_[173].physic           = PHYSIC_NUMERIC;
  scadaParameters_[173].unit             = 0;
  scadaParameters_[173].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[173].coefficient      = 1;
  scadaParameters_[173].min              = 0;
  scadaParameters_[173].max              = 65535;
  // Дата-время
  scadaParameters_[174].id               = 0;
  scadaParameters_[174].address          = 30076;
  scadaParameters_[174].operation        = OPERATION_WRITE;
  scadaParameters_[174].physic           = PHYSIC_NUMERIC;
  scadaParameters_[174].unit             = 0;
  scadaParameters_[174].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[174].coefficient      = 1;
  scadaParameters_[174].min              = 0;
  scadaParameters_[174].max              = 65535;
  // Время
  scadaParameters_[175].id               = 0;
  scadaParameters_[175].address          = 30077;
  scadaParameters_[175].operation        = OPERATION_WRITE;
  scadaParameters_[175].physic           = PHYSIC_NUMERIC;
  scadaParameters_[175].unit             = 0;
  scadaParameters_[175].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[175].coefficient      = 1;
  scadaParameters_[175].min              = 0;
  scadaParameters_[175].max              = 65535;
  // Пароль
  scadaParameters_[176].id               = CCS_PASSWORD_LEVEL_1;
  scadaParameters_[176].address          = 30078;
  scadaParameters_[176].operation        = OPERATION_WRITE;
  scadaParameters_[176].physic           = PHYSIC_NUMERIC;
  scadaParameters_[176].unit             = 0;
  scadaParameters_[176].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[176].coefficient      = 1;
  scadaParameters_[176].min              = 0;
  scadaParameters_[176].max              = 9999;
  // Мастер пароль
  scadaParameters_[177].id               = CCS_PASSWORD_LEVEL_2;
  scadaParameters_[177].address          = 30079;
  scadaParameters_[177].operation        = OPERATION_WRITE;
  scadaParameters_[177].physic           = PHYSIC_NUMERIC;
  scadaParameters_[177].unit             = 0;
  scadaParameters_[177].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[177].coefficient      = 1;
  scadaParameters_[177].min              = 0;
  scadaParameters_[177].max              = 9999;
  // Резерв
  scadaParameters_[178].id               = -1;
  scadaParameters_[178].address          = 30080;
  scadaParameters_[178].operation        = OPERATION_WRITE;
  scadaParameters_[178].physic           = 0;
  scadaParameters_[178].unit             = 0;
  scadaParameters_[178].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[178].coefficient      = 1;
  scadaParameters_[178].min              = 0;
  scadaParameters_[178].max              = 0;
  // Резерв
  scadaParameters_[179].id               = -1;
  scadaParameters_[179].address          = 30081;
  scadaParameters_[179].operation        = OPERATION_WRITE;
  scadaParameters_[179].physic           = 0;
  scadaParameters_[179].unit             = 0;
  scadaParameters_[179].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[179].coefficient      = 1;
  scadaParameters_[179].min              = 0;
  scadaParameters_[179].max              = 0;
  // Резерв
  scadaParameters_[180].id               = -1;
  scadaParameters_[180].address          = 30082;
  scadaParameters_[180].operation        = OPERATION_WRITE;
  scadaParameters_[180].physic           = 0;
  scadaParameters_[180].unit             = 0;
  scadaParameters_[180].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[180].coefficient      = 1;
  scadaParameters_[180].min              = 0;
  scadaParameters_[180].max              = 0;
  // Резерв
  scadaParameters_[181].id               = -1;
  scadaParameters_[181].address          = 30083;
  scadaParameters_[181].operation        = OPERATION_WRITE;
  scadaParameters_[181].physic           = 0;
  scadaParameters_[181].unit             = 0;
  scadaParameters_[181].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[181].coefficient      = 1;
  scadaParameters_[181].min              = 0;
  scadaParameters_[181].max              = 0;
  // Резерв
  scadaParameters_[182].id               = -1;
  scadaParameters_[182].address          = 30084;
  scadaParameters_[182].operation        = OPERATION_WRITE;
  scadaParameters_[182].physic           = 0;
  scadaParameters_[182].unit             = 0;
  scadaParameters_[182].typeData         = TYPE_DATA_UINT16;
  scadaParameters_[182].coefficient      = 1;
  scadaParameters_[182].min              = 0;
  scadaParameters_[182].max              = 0;
}

